// How Starcall works: the AI disclosure, safety rules and the rights-holder process.

import { BadgeCheck, Bot, Mic2, ShieldCheck, UserX, Wand2 } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useI18n, type Key } from '../i18n/index.tsx';
import { api } from '../lib/api.ts';
import { useStore } from '../lib/store.tsx';

function Point({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) {
  return (
    <div className="panel" style={{ display: 'flex', gap: 14 }}>
      <div style={{ color: 'var(--holo)', flex: 'none', marginTop: 2 }}>{icon}</div>
      <div>
        <h3 style={{ margin: '0 0 4px', fontSize: 16 }}>{title}</h3>
        <div className="muted" style={{ fontSize: 14.5 }}>
          {children}
        </div>
      </div>
    </div>
  );
}

export function AboutAI() {
  const { t } = useI18n();
  return (
    <main className="page narrow">
      <div className="page-head">
        <div>
          <h1 className="page-title">{t('disclosure.learn_more')}</h1>
          <p className="page-sub">{t('disclosure.footer')}</p>
        </div>
      </div>
      <div className="stack">
        <Point icon={<Bot size={22} />} title="Every character is an AI simulation">
          Characters are generated by a large language model (Claude) prompted with a public figure’s well-known career and public speaking style. They are not the real people, have no
          connection to them, and are not endorsed by them. Ask any character whether it is real and it will tell you it is an AI.
        </Point>
        <Point icon={<Wand2 size={22} />} title="Stylised avatars, not deepfakes">
          The faces you see are real-time, stylised “holographic” animations rendered in your browser — they don’t reproduce anyone’s real face, and every frame carries an “AI simulation”
          watermark. Photoreal avatars are only enabled for characters whose likeness has been licensed by the rights holder, and are labelled “Licensed likeness”.
        </Point>
        <Point icon={<Mic2 size={22} />} title="Synthetic voices">
          Voices come from your browser’s speech engine or from stock neural voices. They are never cloned from the real person. A voice replica is only used when it has been licensed, and is
          labelled “Licensed voice”.
        </Point>
        <Point icon={<ShieldCheck size={22} />} title="Safety rules the AI can’t break">
          No sexual or romantic content, no hate or harassment, no product, crypto or investment promotion, no requests for money or personal data, no invented private details, and no
          opinions on politics, religion or real controversies attributed to the person. Teens get family-friendly mode automatically and the service is closed to under-13s. Messages that
          mention self-harm get a caring response with crisis resources. You can report any conversation from the call or chat screen.
        </Point>
        <Point icon={<BadgeCheck size={22} />} title="Your data">
          Your camera feed is shown only to you and never uploaded. Microphone audio is transcribed (by your browser or our speech provider) to text; transcripts are saved to your history so
          you can review, download or delete them at any time.
        </Point>
        <Point icon={<UserX size={22} />} title="Opt-outs and removals">
          People who have publicly objected to AI replicas of themselves are not on Starcall. If you are featured, or represent someone who is, you can ask for removal at any time —{' '}
          <Link to="/rights" style={{ textDecoration: 'underline' }}>
            {t('rights.title')}
          </Link>
          .
        </Point>
      </div>
    </main>
  );
}

export function Rights() {
  const { t } = useI18n();
  const { toast } = useStore();
  const [params] = useSearchParams();
  const [done, setDone] = useState(false);
  const [form, setForm] = useState({
    characterId: params.get('character') ?? '',
    subjectName: params.get('name') ?? '',
    requesterName: '',
    relationship: 'self',
    email: '',
    requestType: 'removal',
    details: '',
  });
  const submit = async (e: FormEvent) => {
    e.preventDefault();
    try {
      await api.rights(form);
      setDone(true);
    } catch {
      toast(t('common.error'), true);
    }
  };
  return (
    <main className="page narrow">
      <div className="page-head">
        <div>
          <h1 className="page-title">{t('rights.title')}</h1>
          <p className="page-sub">{t('rights.sub')}</p>
        </div>
      </div>
      {done ? (
        <div className="banner info">{t('rights.thanks')}</div>
      ) : (
        <form className="panel stack" onSubmit={submit}>
          <div className="form-grid">
            <div className="field">
              <label htmlFor="r-subject">{t('rights.subject')}</label>
              <input id="r-subject" className="input" required value={form.subjectName} onChange={(e) => setForm({ ...form, subjectName: e.target.value })} />
            </div>
            <div className="field">
              <label htmlFor="r-name">{t('rights.requester')}</label>
              <input id="r-name" className="input" required value={form.requesterName} onChange={(e) => setForm({ ...form, requesterName: e.target.value })} />
            </div>
            <div className="field">
              <label htmlFor="r-rel">{t('rights.relationship')}</label>
              <select id="r-rel" className="select" value={form.relationship} onChange={(e) => setForm({ ...form, relationship: e.target.value })}>
                {['self', 'agent', 'legal', 'estate'].map((r) => (
                  <option key={r} value={r}>
                    {t(`rights.rel.${r}` as Key)}
                  </option>
                ))}
              </select>
            </div>
            <div className="field">
              <label htmlFor="r-email">{t('rights.email')}</label>
              <input id="r-email" type="email" className="input" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />
            </div>
            <div className="field">
              <label htmlFor="r-type">{t('rights.type')}</label>
              <select id="r-type" className="select" value={form.requestType} onChange={(e) => setForm({ ...form, requestType: e.target.value })}>
                {['removal', 'correction', 'licensing'].map((r) => (
                  <option key={r} value={r}>
                    {t(`rights.t.${r}` as Key)}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div className="field">
            <label htmlFor="r-details">{t('rights.details')}</label>
            <textarea id="r-details" className="textarea" value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} maxLength={2000} />
          </div>
          <div className="row" style={{ justifyContent: 'flex-end' }}>
            <button className="btn primary">{t('rights.submit')}</button>
          </div>
        </form>
      )}
    </main>
  );
}
