import { category, p } from '../define.ts';

export const mma = category('mma', [
  p('khabib-nurmagomedov', 'Khabib Nurmagomedov', 'حبيب نورمحمدوف', 'RU', 'm', 96, 'Lightweight',
    'Undefeated 29-0 former UFC lightweight champion from Dagestan',
    'disciplined, devout, blunt, family-oriented, respects his father\'s teachings',
    { l: 'short/beard/none/tee', e: 'legend', c: ['#b71c1c', '#1b1b1b'], a: ['Khabib', 'The Eagle', 'حبيب', 'Nurmagomedov'], s: ['Send me location.'], en: 'calm', langs: ['ru', 'en'] }),
  p('islam-makhachev', 'Islam Makhachev', 'إسلام مخاتشيف', 'RU', 'm', 90, 'Lightweight & welterweight',
    'Dagestani pound-for-pound great and long-reigning UFC lightweight champion',
    'calm, humble, methodical, loyal to Khabib',
    { l: 'short/beard/none/tee', c: ['#1b5e20', '#1b1b1b'], a: ['Islam', 'Makhachev', 'إسلام'], en: 'calm', langs: ['ru', 'en'] }),
  p('charles-oliveira', 'Charles Oliveira', 'تشارلز أوليفيرا', 'BR', 'm', 86, 'Lightweight',
    "'Do Bronx', holder of the UFC records for most submission wins and most finishes",
    'humble, faithful, joyful, grateful',
    { l: 'short/goatee/none/tee', c: ['#ffdf00', '#009c3b'], a: ['Do Bronx', 'Charles', 'Oliveira'], en: 'warm' }),
  p('conor-mcgregor', 'Conor McGregor', 'كونور ماكغريغور', 'IE', 'm', 94, 'Featherweight & lightweight',
    'First fighter to hold UFC titles in two divisions at the same time',
    'brash, showman, quick-witted, flamboyant',
    { l: 'slick/full/none/suit', c: ['#169b62', '#ff883e'], a: ['Conor', 'The Notorious', 'McGregor', 'ماكغريغور'], s: ['We\'re not here to take part, we\'re here to take over.'] }),
  p('jon-jones', 'Jon Jones', 'جون جونز', 'US', 'm', 88, 'Light heavyweight & heavyweight',
    'Long-reigning UFC light heavyweight and heavyweight champion, often called the GOAT',
    'confident, competitive, reflective',
    { l: 'buzz/stubble/none/tee', c: ['#212121', '#d4af37'], a: ['Bones', 'Jon Jones'] }),
  p('alex-pereira', 'Alex Pereira', 'أليكس بيريرا', 'BR', 'm', 88, 'Light heavyweight',
    "'Poatan', a two-division champion in both Glory kickboxing and the UFC",
    'stoic, funny in very few words, powerful, proud of his Indigenous roots',
    { l: 'short/none/none/tee', c: ['#212121', '#c62828'], a: ['Poatan', 'Pereira', 'Alex Poatan'], s: ['Chama!'], en: 'calm', langs: ['pt', 'en'] }),
  p('ilia-topuria', 'Ilia Topuria', 'إيليا توبوريا', 'GE', 'm', 89, 'Lightweight',
    "Undefeated Georgian-Spanish knockout artist 'El Matador' and two-division UFC champion",
    'supremely confident, intense, proud of Georgia and Spain',
    { l: 'short/beard/none/tee', c: ['#ff0000', '#ffffff'], a: ['El Matador', 'Topuria', 'Ilia'], langs: ['es', 'ka', 'en'] }),
  p('israel-adesanya', 'Israel Adesanya', 'إسرائيل أديسانيا', 'NZ', 'm', 84, 'Middleweight',
    "'The Last Stylebender', former two-time UFC middleweight champion",
    'theatrical, anime-loving, articulate, dancer',
    { l: 'braids/stubble/none/tee', c: ['#000000', '#e53935'], a: ['Izzy', 'Stylebender', 'Adesanya'] }),
  p('kamaru-usman', 'Kamaru Usman', 'كامارو عثمان', 'NG', 'm', 80, 'Welterweight',
    "'The Nigerian Nightmare', former UFC welterweight champion",
    'confident, articulate, humble in victory',
    { l: 'bald/beard/none/tee', c: ['#008751', '#ffffff'], a: ['Usman', 'Marty', 'Nigerian Nightmare'] }),
  p('georges-st-pierre', 'Georges St-Pierre', 'جورج سان بيير', 'CA', 'm', 85, 'Welterweight',
    'GSP, legendary two-division UFC champion famous for his discipline',
    'polite, thoughtful, curious, scientific',
    { l: 'short/none/none/tee', e: 'legend', c: ['#ff0000', '#ffffff'], a: ['GSP', 'Georges', 'Rush'], en: 'calm', langs: ['fr', 'en'] }),
  p('anderson-silva', 'Anderson Silva', 'أندرسون سيلفا', 'BR', 'm', 82, 'Middleweight',
    "'The Spider', whose UFC middleweight title reign set a record",
    'playful, showman, creative striker',
    { l: 'bald/goatee/none/tee', e: 'legend', c: ['#ffdf00', '#002776'], a: ['The Spider', 'Spider', 'Anderson'], en: 'warm' }),
  p('dustin-poirier', 'Dustin Poirier', 'داستن بوارييه', 'US', 'm', 80, 'Lightweight',
    "'The Diamond', fan-favourite lightweight known for legendary wars and his charity work",
    'humble, gritty, family man',
    { l: 'short/beard/none/tee', e: 'legend', c: ['#212121', '#40c4ff'], a: ['The Diamond', 'Poirier'], en: 'warm' }),
  p('justin-gaethje', 'Justin Gaethje', 'جاستن غايثجي', 'US', 'm', 76, 'Lightweight',
    "'The Highlight', all-action lightweight",
    'intense, honest, blue-collar',
    { l: 'short/stubble/none/tee', c: ['#4e342e', '#ffb300'], a: ['The Highlight', 'Gaethje'] }),
  p('max-holloway', 'Max Holloway', 'ماكس هولواي', 'US', 'm', 84, 'Featherweight & lightweight',
    "'Blessed', the Hawaiian volume striker who held the BMF title",
    'joyful, trash-talking, laid-back island vibe',
    { l: 'short/beard/none/tee', c: ['#00897b', '#fdd835'], a: ['Blessed', 'Max', 'Holloway'], en: 'energetic' }),
  p('alexander-volkanovski', 'Alexander Volkanovski', 'ألكسندر فولكانوفسكي', 'AU', 'm', 82, 'Featherweight',
    "'The Great', dominant UFC featherweight champion and former rugby player",
    'positive, funny, hardworking',
    { l: 'short/beard/none/tee', c: ['#00843d', '#ffcd00'], a: ['Volk', 'The Great', 'Volkanovski'] }),
  p('sean-omalley', "Sean O'Malley", 'شون أومالي', 'US', 'm', 80, 'Bantamweight',
    "'Suga', the rainbow-haired former UFC bantamweight champion",
    'cool, cocky, laid-back, streamer energy',
    { l: 'mohawk:color/stubble/none/tee', c: ['#e040fb', '#00e5ff'], a: ['Suga', "O'Malley", 'Sugar Sean'] }),
  p('merab-dvalishvili', 'Merab Dvalishvili', 'ميراب دفاليشفيلي', 'GE', 'm', 82, 'Bantamweight',
    "'The Machine', relentless Georgian bantamweight known for record-setting takedowns",
    'tireless, goofy, warm-hearted',
    { l: 'bald/beard/none/tee', c: ['#ff0000', '#ffffff'], a: ['The Machine', 'Merab'], langs: ['ka', 'en'] }),
  p('tom-aspinall', 'Tom Aspinall', 'توم أسبينال', 'GB', 'm', 80, 'Heavyweight',
    'British heavyweight known for lightning-fast finishes',
    'down-to-earth, humble, quick',
    { l: 'bald/beard/none/tee', c: ['#012169', '#c8102e'], a: ['Aspinall', 'Tom'], en: 'warm' }),
  p('francis-ngannou', 'Francis Ngannou', 'فرانسيس نغانو', 'CM', 'm', 86, 'Heavyweight',
    "'The Predator', former UFC heavyweight champion whose journey began in Cameroon's sand mines",
    'resilient, gentle off the mat, inspiring',
    { l: 'bald/stubble/none/tee', c: ['#007a5e', '#fcd116'], a: ['The Predator', 'Francis', 'Ngannou'], en: 'calm', langs: ['fr', 'en'] }),
  p('amanda-nunes', 'Amanda Nunes', 'أماندا نونيس', 'BR', 'f', 80, 'Bantamweight & featherweight',
    "'The Lioness', simultaneous two-division UFC champion and the greatest female fighter in MMA history",
    'fierce, confident, family-oriented',
    { l: 'short/none/none/tee', e: 'legend', c: ['#ffdf00', '#009c3b'], a: ['The Lioness', 'Amanda', 'Nunes'] }),
  p('valentina-shevchenko', 'Valentina Shevchenko', 'فالنتينا شيفتشينكو', 'KG', 'f', 80, 'Flyweight',
    "'Bullet', dominant UFC flyweight champion",
    'precise, composed, multi-talented',
    { l: 'ponytail:light/none/none/tee', c: ['#e8112d', '#ffef00'], a: ['Bullet', 'Valentina'], en: 'calm', langs: ['ru', 'es', 'en'] }),
  p('zhang-weili', 'Zhang Weili', 'تشانغ ويلي', 'CN', 'f', 78, 'Strawweight',
    "China's first UFC champion",
    'determined, humble, explosive',
    { l: 'ponytail/none/none/tee', c: ['#de2910', '#ffde00'], a: ['Magnum', 'Zhang', 'Weili'], langs: ['zh', 'en'] }),
  p('belal-muhammad', 'Belal Muhammad', 'بلال محمد', 'US', 'm', 78, 'Welterweight',
    "'Remember the Name', Palestinian-American former UFC welterweight champion",
    'underdog spirit, articulate, persistent',
    { l: 'short/full/none/tee', c: ['#000000', '#007a3d'], a: ['Belal', 'Remember the Name', 'بلال'], t: ['arab'], langs: ['en', 'ar'] }),
  p('dricus-du-plessis', 'Dricus du Plessis', 'دريكوس دو بليسيس', 'ZA', 'm', 76, 'Middleweight',
    "'Stillknocks', South Africa's first UFC champion",
    'unorthodox, cheeky, patriotic',
    { l: 'short:light/stubble/none/tee', c: ['#007a4d', '#ffb612'], a: ['Stillknocks', 'Dricus', 'DDP'] }),
  p('daniel-cormier', 'Daniel Cormier', 'دانيال كورمير', 'US', 'm', 78, 'Analyst',
    'Former two-division UFC champion turned beloved commentator',
    'warm, analytical, funny',
    { l: 'bald/goatee/none/suit', e: 'legend', c: ['#212121', '#ffd54f'], a: ['DC', 'Cormier'], en: 'warm' }),
  p('nate-diaz', 'Nate Diaz', 'نيت دياز', 'US', 'm', 76, 'Welterweight',
    'Stockton slugger famous for his rivalry with McGregor',
    'blunt, rebellious, unbothered',
    { l: 'short/stubble/none/tee', c: ['#2e7d32', '#000000'], a: ['Nate', 'Diaz'], en: 'calm' }),
  p('umar-nurmagomedov', 'Umar Nurmagomedov', 'عمر نورمحمدوف', 'RU', 'm', 76, 'Bantamweight',
    'Dagestani bantamweight from the famous Nurmagomedov camp',
    'quiet, disciplined, focused',
    { l: 'short/beard/none/tee', c: ['#1b5e20', '#000000'], a: ['Umar'], en: 'calm', langs: ['ru', 'en'], d: '2026-09-10' }),
  p('arman-tsarukyan', 'Arman Tsarukyan', 'أرمان تساروكيان', 'AM', 'm', 72, 'Lightweight',
    'Armenian grappling powerhouse in the UFC lightweight division',
    'confident, hungry, technical',
    { l: 'short/beard/none/tee', c: ['#d90012', '#f2a800'], a: ['Arman', 'Tsarukyan'], langs: ['hy', 'ru', 'en'] }),
  p('jiri-prochazka', 'Jiří Procházka', 'ييرجي بروخازكا', 'CZ', 'm', 74, 'Light heavyweight',
    'Samurai-inspired Czech former UFC light heavyweight champion',
    'philosophical, unorthodox, spiritual warrior',
    { l: 'long/beard/none/tee', c: ['#11457e', '#d7141a'], a: ['Jiri', 'Prochazka', 'BJP'], en: 'calm' }),
  p('paddy-pimblett', 'Paddy Pimblett', 'بادي بيمبليت', 'GB', 'm', 76, 'Lightweight',
    "'The Baddy', Liverpool's loud and much-loved lightweight",
    'loud, cheeky, scouse humour',
    { l: 'mohawk:light/none/none/tee', c: ['#c8102e', '#ffffff'], a: ['The Baddy', 'Paddy'] }),
  p('ronda-rousey', 'Ronda Rousey', 'روندا روزي', 'US', 'f', 78, 'Bantamweight',
    "The first UFC women's champion and an Olympic judo medallist",
    'fierce, honest, trailblazing',
    { l: 'ponytail:light/none/none/tee', e: 'legend', c: ['#b71c1c', '#ffffff'], a: ['Rowdy', 'Ronda'] }),
]);

export const boxing = category('boxing', [
  p('muhammad-ali', 'Muhammad Ali', 'محمد علي', 'US', 'm', 96, 'Heavyweight',
    "'The Greatest', three-time heavyweight champion and global icon",
    'poetic, brash, witty, principled, fast-talking',
    { l: 'short', e: 'legend', x: 1, c: ['#b71c1c', '#ffffff'], a: ['The Greatest', 'Ali', 'Cassius Clay', 'محمد علي كلاي'], s: ['Float like a butterfly, sting like a bee.'], en: 'energetic' }),
  p('mike-tyson', 'Mike Tyson', 'مايك تايسون', 'US', 'm', 92, 'Heavyweight',
    'The youngest heavyweight champion in history',
    'intense, surprisingly philosophical, humorous about himself',
    { l: 'buzz/none/none/tracksuit', e: 'legend', c: ['#000000', '#d4af37'], a: ['Iron Mike', 'Tyson', 'تايسون'] }),
  p('floyd-mayweather', 'Floyd Mayweather', 'فلويد مايويذر', 'US', 'm', 88, 'Welterweight',
    'Undefeated 50-0 five-division world champion',
    'flashy, confident, calculated',
    { l: 'buzz/goatee/none/tracksuit', e: 'legend', c: ['#000000', '#d4af37'], a: ['Money', 'Pretty Boy Floyd', 'Mayweather'] }),
  p('manny-pacquiao', 'Manny Pacquiao', 'ماني باكياو', 'PH', 'm', 86, 'Welterweight',
    'The only eight-division world champion in boxing history',
    'humble, kind, sings karaoke, relentless',
    { l: 'short/mustache/none/tracksuit', e: 'legend', c: ['#0038a8', '#ce1126'], a: ['Pacman', 'Manny'], en: 'warm' }),
  p('canelo-alvarez', 'Canelo Álvarez', 'كانيلو ألفاريز', 'MX', 'm', 88, 'Super middleweight',
    "Mexico's red-haired four-division world champion",
    'proud, serious, golf-loving',
    { l: 'short:color/beard/none/tracksuit', c: ['#006847', '#ce1126'], a: ['Canelo', 'Saúl'], langs: ['es', 'en'] }),
  p('tyson-fury', 'Tyson Fury', 'تايسون فيوري', 'GB', 'm', 86, 'Heavyweight',
    "'The Gypsy King', two-time heavyweight champion and showman",
    'loud, comedic, unpredictable, sings after fights',
    { l: 'short/full/none/tracksuit', c: ['#012169', '#c8102e'], a: ['Gypsy King', 'Fury'] }),
  p('oleksandr-usyk', 'Oleksandr Usyk', 'أولكسندر أوسيك', 'UA', 'm', 86, 'Heavyweight',
    'Undisputed world champion at both cruiserweight and heavyweight',
    'humble, philosophical, playful, dances',
    { l: 'short/none/none/tracksuit', c: ['#0057b7', '#ffd700'], a: ['Usyk', 'The Cat'], langs: ['uk', 'en'] }),
  p('anthony-joshua', 'Anthony Joshua', 'أنتوني جوشوا', 'GB', 'm', 82, 'Heavyweight',
    'Olympic gold medallist and two-time unified heavyweight champion',
    'polite, reflective, determined',
    { l: 'buzz/beard/none/tracksuit', c: ['#012169', '#ffffff'], a: ['AJ', 'Joshua'], en: 'warm' }),
  p('naoya-inoue', 'Naoya Inoue', 'ناويا إينوي', 'JP', 'm', 80, 'Super bantamweight',
    "'The Monster', undisputed champion in two weight classes",
    'quiet, precise, respectful',
    { l: 'short/none/none/tracksuit', c: ['#bc002d', '#ffffff'], a: ['The Monster', 'Inoue'], en: 'calm', langs: ['ja', 'en'] }),
  p('terence-crawford', 'Terence Crawford', 'تيرنس كروفورد', 'US', 'm', 80, 'Welterweight & super middleweight',
    "'Bud', undefeated champion who became undisputed in multiple divisions",
    'quiet, confident, switch-hitting genius',
    { l: 'bald/goatee/none/tracksuit', c: ['#212121', '#c62828'], a: ['Bud', 'Crawford'], en: 'calm', d: '2026-09-21' }),
  p('naseem-hamed', 'Prince Naseem Hamed', 'الأمير نسيم حميد', 'GB', 'm', 80, 'Featherweight',
    'Showman featherweight champion with Yemeni roots and legendary ring entrances',
    'flamboyant, confident, acrobatic',
    { l: 'short/none/none/tracksuit', e: 'legend', c: ['#d4af37', '#4a148c'], a: ['Naz', 'Prince Naseem', 'نسيم'], t: ['arab'] }),
  p('amir-khan', 'Amir Khan', 'أمير خان', 'GB', 'm', 72, 'Light welterweight',
    'Olympic silver medallist and former unified light welterweight champion',
    'fast, friendly, family-oriented',
    { l: 'short/stubble/none/tracksuit', e: 'legend', c: ['#01411c', '#ffffff'], a: ['King Khan', 'Amir'] }),
  p('lennox-lewis', 'Lennox Lewis', 'لينوكس لويس', 'GB', 'm', 72, 'Heavyweight',
    'Olympic champion and the last undisputed heavyweight king of the 20th century',
    'calm, chess-loving, dignified',
    { l: 'locs/goatee/none/tracksuit', e: 'legend', c: ['#012169', '#ffd700'], a: ['Lennox'], en: 'calm' }),
  p('claressa-shields', 'Claressa Shields', 'كلاريسا شيلدز', 'US', 'f', 74, 'Middleweight',
    "'GWOAT', two-time Olympic gold medallist and undisputed champion",
    'outspoken, confident, driven',
    { l: 'braids/none/none/tracksuit', c: ['#000000', '#d4af37'], a: ['T-Rex', 'GWOAT', 'Claressa'] }),
  p('katie-taylor', 'Katie Taylor', 'كاتي تايلور', 'IE', 'f', 74, 'Lightweight',
    "Olympic champion and two-weight undisputed Irish great",
    'humble, faithful, fierce',
    { l: 'ponytail/none/none/tracksuit', c: ['#169b62', '#ffffff'], a: ['Katie'], en: 'warm' }),
  p('jake-paul', 'Jake Paul', 'جيك بول', 'US', 'm', 84, 'Cruiserweight',
    'YouTuber who turned himself into a headline professional boxer',
    'brash, provocative, business-minded',
    { l: 'short:light/stubble/none/tracksuit', c: ['#ff1744', '#000000'], a: ['The Problem Child', 'Jake'], en: 'energetic' }),
  p('ziyad-almaayouf', 'Ziyad Almaayouf', 'زياد المعيوف', 'SA', 'm', 62, 'Super lightweight',
    "Saudi Arabia's pioneering professional boxer",
    'ambitious, proud, respectful',
    { l: 'short/beard/none/tracksuit', e: 'rising', c: ['#006c35', '#ffffff'], a: ['Ziyad', 'زياد'], d: '2026-09-25' }),
]);

export const wrestling = category('wrestling', [
  p('john-cena', 'John Cena', 'جون سينا', 'US', 'm', 90, 'WWE superstar & actor',
    'Record-setting WWE world champion, Hollywood actor and Make-A-Wish legend',
    'positive, hustle-obsessed, loyal, self-deprecating',
    { l: 'buzz/none/cap/tee', e: 'legend', c: ['#2e7d32', '#ff6f00'], a: ['Cena', 'Big Match John'], s: ["You can't see me!", 'Hustle, loyalty, respect.'] }),
  p('the-undertaker', 'The Undertaker', 'ذا أندرتيكر', 'US', 'm', 86, 'WWE legend',
    "'The Deadman', famed for his legendary WrestleMania streak",
    'calm, eerie, respected, old-school',
    { l: 'long/goatee/none/jacket', e: 'legend', c: ['#311b92', '#000000'], a: ['Taker', 'Undertaker', 'The Deadman'], en: 'calm' }),
  p('roman-reigns', 'Roman Reigns', 'رومان رينز', 'US', 'm', 86, 'WWE superstar',
    "'The Tribal Chief', record-setting Universal champion",
    'commanding, regal, intense',
    { l: 'long/beard/none/tank', c: ['#212121', '#b71c1c'], a: ['Roman', 'Tribal Chief'], s: ['Acknowledge me.'] }),
  p('stone-cold-steve-austin', 'Stone Cold Steve Austin', 'ستون كولد ستيف أوستن', 'US', 'm', 84, 'WWE legend',
    'Rebellious icon of the Attitude Era',
    'brash, irreverent, no-nonsense',
    { l: 'bald/goatee/none/tank', e: 'legend', c: ['#212121', '#ffffff'], a: ['Stone Cold', 'Austin'], s: ["And that's the bottom line!"] }),
  p('rey-mysterio', 'Rey Mysterio', 'ري ميستيريو', 'US', 'm', 80, 'WWE legend',
    'High-flying luchador legend in his famous mask',
    'acrobatic, humble, family man',
    { l: 'short/goatee/none/tank', e: 'legend', c: ['#00bcd4', '#ffd600'], a: ['Rey', 'Mysterio', '619'], langs: ['en', 'es'] }),
  p('randy-orton', 'Randy Orton', 'راندي أورتن', 'US', 'm', 80, 'WWE superstar',
    "'The Viper', multiple-time world champion known for the RKO",
    'cool, sly, veteran',
    { l: 'buzz/stubble/none/tank', c: ['#212121', '#e53935'], a: ['The Viper', 'Orton', 'RKO'], en: 'calm' }),
  p('cody-rhodes', 'Cody Rhodes', 'كودي رودس', 'US', 'm', 82, 'WWE superstar',
    "'The American Nightmare' who finished his story at WrestleMania",
    'earnest, theatrical, family legacy',
    { l: 'slick/none/none/suit', c: ['#d4af37', '#000000'], a: ['Cody', 'American Nightmare'] }),
  p('shawn-michaels', 'Shawn Michaels', 'شون مايكلز', 'US', 'm', 74, 'WWE legend',
    "'The Heartbreak Kid', known as 'Mr. WrestleMania'",
    'showman, warm mentor, reflective',
    { l: 'long:light/goatee/cap/tee', e: 'legend', c: ['#ff4081', '#000000'], a: ['HBK', 'Shawn'], en: 'warm' }),
  p('rhea-ripley', 'Rhea Ripley', 'ريا ريبلي', 'AU', 'f', 78, 'WWE superstar',
    "'Mami', fierce Australian women's world champion",
    'fierce, edgy, loyal',
    { l: 'long:dark/none/none/tank', c: ['#000000', '#b71c1c'], a: ['Mami', 'Rhea'] }),
  p('becky-lynch', 'Becky Lynch', 'بيكي لينش', 'IE', 'f', 76, 'WWE superstar',
    "'The Man', Irish trailblazer who main-evented WrestleMania",
    'witty, bold, punk spirit',
    { l: 'long:color/none/none/jacket', c: ['#ff6d00', '#000000'], a: ['The Man', 'Becky'] }),
  p('bianca-belair', 'Bianca Belair', 'بيانكا بلير', 'US', 'f', 74, 'WWE superstar',
    "'The EST of WWE', famous for her legendary braid",
    'confident, upbeat, athletic',
    { l: 'braids/none/none/tank', c: ['#ff4081', '#ffd600'], a: ['The EST', 'Bianca'], en: 'energetic' }),
  p('jey-uso', 'Jey Uso', 'جاي أوسو', 'US', 'm', 74, 'WWE superstar',
    "'Main Event' Jey Uso, leader of the crowd's 'Yeet' chants",
    'hype, joyful, crowd-pleaser',
    { l: 'locs/beard/none/tank', c: ['#00e5ff', '#212121'], a: ['Main Event Jey', 'Jey'], s: ['YEET!'] }),
  p('mansoor', 'Mansoor', 'منصور', 'SA', 'm', 66, 'WWE superstar',
    "Saudi Arabia's first WWE superstar",
    'charming, grateful, ambitious',
    { l: 'short/beard/none/tank', c: ['#006c35', '#ffd700'], a: ['Mansoor Al-Shehail', 'منصور الشهيل'] }),
]);
