import { category, p } from '../define.ts';

export const creators = category('creators', [
  p('mrbeast', 'MrBeast', 'مستر بيست', 'US', 'm', 98, 'YouTuber',
    'Creator of the most-subscribed YouTube channel, famous for giant challenges and giveaways',
    'generous, hyper, ambitious, competitive, obsessed with retention',
    { l: 'short/beard/none/hoodie', c: ['#4ad3ff', '#ff3fa4'], a: ['Mr Beast', 'Jimmy', 'Jimmy Donaldson', 'Beast', 'مستر بيست'] }),
  p('ishowspeed', 'IShowSpeed', 'آي شو سبيد', 'US', 'm', 96, 'Streamer',
    'Hyper-energetic streamer famous for wild live streams, world tours and backflips',
    'loud, chaotic, wholesome, huge Ronaldo fan',
    { l: 'fade/none/none/hoodie', c: ['#ff1744', '#ffd600'], a: ['Speed', 'Darren', 'سبيد'], s: ['Siuuu!'] }),
  p('kai-cenat', 'Kai Cenat', 'كاي سينات', 'US', 'm', 93, 'Streamer',
    'Record-breaking Twitch streamer behind the famous Mafiathon subathons',
    'funny, hype, loyal to his community',
    { l: 'fade/none/none/hoodie', c: ['#9146ff', '#00e5ff'], a: ['Kai', 'Cenat'] }),
  p('pewdiepie', 'PewDiePie', 'بيو دي باي', 'SE', 'm', 90, 'YouTuber',
    'Swedish gaming YouTuber who pioneered modern creator culture',
    'witty, ironic, relaxed, nerdy hobbies',
    { l: 'short:light/beard/none/hoodie', e: 'legend', c: ['#ff1744', '#000000'], a: ['Pewds', 'Felix', 'PewDiePie'], en: 'warm' }),
  p('markiplier', 'Markiplier', 'ماركيبلاير', 'US', 'm', 82, 'YouTuber',
    'Horror-game YouTuber, filmmaker and charity streamer',
    'goofy, heartfelt, dramatic',
    { l: 'wavy/stubble/none/hoodie', c: ['#e53935', '#ff8a80'], a: ['Mark', 'Markiplier'] }),
  p('ninja', 'Ninja', 'نينجا', 'US', 'm', 82, 'Streamer',
    'Fortnite streaming pioneer with his signature dyed hair and headband',
    'competitive, upbeat, family-friendly',
    { l: 'short:color/none/headband/hoodie', c: ['#00e5ff', '#ffeb3b'], a: ['Ninja', 'Tyler Blevins'] }),
  p('pokimane', 'Pokimane', 'بوكيمين', 'CA', 'f', 78, 'Streamer',
    'Variety streamer and creator-entrepreneur',
    'friendly, thoughtful, wholesome',
    { l: 'long/none/headphones/hoodie', c: ['#e040fb', '#00e5ff'], a: ['Poki', 'Imane'], en: 'warm' }),
  p('ksi', 'KSI', 'كي إس آي', 'GB', 'm', 86, 'YouTuber & musician',
    'Sidemen star, musician and boxer',
    'competitive, loud laugh, self-roasting',
    { l: 'fade/none/none/hoodie', c: ['#ff3d00', '#212121'], a: ['JJ', 'KSI'] }),
  p('mark-rober', 'Mark Rober', 'مارك روبر', 'US', 'm', 82, 'YouTuber',
    'Former NASA engineer making science videos with epic builds',
    'curious, nerdy, playful, educational',
    { l: 'short:light/none/none/tee', c: ['#ff6d00', '#2979ff'], a: ['Rober', 'Mark'], env: 'lab', en: 'warm' }),
  p('mkbhd', 'Marques Brownlee', 'ماركيز براونلي', 'US', 'm', 80, 'Tech YouTuber',
    'MKBHD, the internet’s most trusted tech reviewer',
    'calm, precise, design-focused',
    { l: 'buzz/goatee/none/tee', c: ['#ff1744', '#212121'], a: ['MKBHD', 'Marques'], en: 'calm' }),
  p('mrwhosetheboss', 'Mrwhosetheboss', 'مستر هوز ذا بوس', 'GB', 'm', 76, 'Tech YouTuber',
    "Arun Maini, the UK's favourite smartphone explainer",
    'enthusiastic, clear, gadget-obsessed',
    { l: 'short/none/none/tee', c: ['#00e676', '#212121'], a: ['Arun', 'Mrwhosetheboss'], en: 'warm' }),
  p('ibai-llanos', 'Ibai Llanos', 'إيباي يانوس', 'ES', 'm', 82, 'Streamer',
    "Spain's record-breaking streamer behind 'La Velada del Año'",
    'funny, friendly, football-mad',
    { l: 'short/beard/none/hoodie', c: ['#ff1744', '#ffd600'], a: ['Ibai'], langs: ['es', 'en'] }),
  p('elrubius', 'El Rubius', 'الروبيوس', 'ES', 'm', 76, 'YouTuber',
    'Spanish gaming YouTube pioneer',
    'goofy, chill, imaginative',
    { l: 'short:light/stubble/none/hoodie', c: ['#ff4081', '#448aff'], a: ['Rubius', 'Rubén'], langs: ['es', 'en'] }),
  p('auronplay', 'AuronPlay', 'أورون بلاي', 'ES', 'm', 74, 'Streamer',
    'Spanish comedy streamer and YouTuber',
    'sarcastic, quick-witted, playful',
    { l: 'short/beard/none/hoodie', c: ['#00e5ff', '#ff4081'], a: ['Auron'], langs: ['es', 'en'] }),
  p('casimiro', 'Casimiro', 'كازيميرو', 'BR', 'm', 76, 'Streamer',
    "Brazil's beloved sports streamer known as 'Casimito'",
    'hilarious, warm, football fanatic',
    { l: 'short/beard/none/hoodie', c: ['#ffdf00', '#009c3b'], a: ['Casimito', 'Cazé'], langs: ['pt', 'en'] }),
  p('squeezie', 'Squeezie', 'سكويزي', 'FR', 'm', 76, 'YouTuber',
    "France's biggest YouTuber and organiser of the GP Explorer race",
    'funny, inventive, friendly',
    { l: 'short/stubble/none/hoodie', c: ['#2979ff', '#ffeb3b'], a: ['Squeezie', 'Lucas'], langs: ['fr', 'en'] }),
  p('khaby-lame', 'Khaby Lame', 'خابي لام', 'IT', 'm', 88, 'TikToker',
    'One of TikTok’s most-followed creators, famous for silent life-hack reactions',
    'deadpan, expressive, says little, shrugs a lot',
    { l: 'fade/none/none/tee', c: ['#00f2ea', '#ff0050'], a: ['Khaby', 'خابي'], en: 'calm', langs: ['it', 'fr', 'en'] }),
  p('charli-damelio', "Charli D'Amelio", 'تشارلي داميليو', 'US', 'f', 78, 'TikToker',
    'Dancing TikTok star and one of the platform’s most-followed creators',
    'sweet, relatable, dancer',
    { l: 'long', c: ['#00f2ea', '#ff0050'], a: ['Charli'], en: 'warm' }),
  p('emma-chamberlain', 'Emma Chamberlain', 'إيما تشامبرلين', 'US', 'f', 74, 'YouTuber',
    'Lifestyle vlogger who redefined the casual YouTube style',
    'quirky, honest, coffee-obsessed',
    { l: 'bob', c: ['#8d6e63', '#ffccbc'], a: ['Emma'], en: 'warm' }),
  p('lilly-singh', 'Lilly Singh', 'ليلي سينغ', 'CA', 'f', 72, 'YouTuber & host',
    'Canadian creator, comedian and talk-show host',
    'funny, motivational, bold',
    { l: 'long', c: ['#ff9100', '#7c4dff'], a: ['Superwoman', 'Lilly'] }),
  p('bhuvan-bam', 'Bhuvan Bam', 'بوفان بام', 'IN', 'm', 72, 'YouTuber',
    "Indian comedy creator behind 'BB Ki Vines'",
    'witty, musical, observational',
    { l: 'short/beard/none/hoodie', c: ['#ff9933', '#138808'], a: ['BB', 'Bhuvan'], langs: ['hi', 'en'] }),
  p('carryminati', 'CarryMinati', 'كاري ميناتي', 'IN', 'm', 74, 'YouTuber',
    "India's roast-comedy YouTube star",
    'loud, sarcastic, gamer',
    { l: 'long/beard/none/hoodie', c: ['#ff1744', '#212121'], a: ['Carry', 'Ajey'], langs: ['hi', 'en'] }),
  p('aboflah', 'AboFlah', 'أبو فلة', 'KW', 'm', 84, 'YouTuber',
    'Kuwaiti creator who set a Guinness World Record with his charity livestream',
    'kind, funny, generous, wholesome',
    { l: 'short/beard/none/hoodie', c: ['#00e676', '#2979ff'], a: ['Abo Flah', 'Abu Fulla', 'أبوفلة', 'حسن سليمان'], langs: ['ar', 'en'] }),
  p('banderitax', 'BanderitaX', 'بندريتا', 'SA', 'm', 76, 'YouTuber',
    'Saudi gaming and comedy YouTuber with a huge Arab audience',
    'funny, chill, gamer',
    { l: 'short/beard/none/hoodie', c: ['#ffd600', '#00b0ff'], a: ['Bander', 'بندر', 'Banderita'], langs: ['ar', 'en'] }),
  p('mo-vlogs', 'Mo Vlogs', 'مو فلوقز', 'AE', 'm', 72, 'Vlogger',
    'Dubai-based vlogger known for supercars and lifestyle videos',
    'energetic, flashy, friendly',
    { l: 'fade/beard/none/tee', c: ['#ffd600', '#212121'], a: ['Mo', 'Mo Vlogs'], langs: ['ar', 'en'] }),
  p('joe-hattab', 'Joe Hattab', 'جو حطاب', 'JO', 'm', 74, 'Travel creator',
    "Jordanian travel vlogger exploring the world's hidden places",
    'curious, adventurous, storyteller',
    { l: 'short/beard/none/jacket', c: ['#007a3d', '#ce1126'], a: ['Joe', 'جو'], langs: ['ar', 'en'], en: 'warm' }),
  p('ahmad-alshugairi', 'Ahmad Al-Shugairi', 'أحمد الشقيري', 'SA', 'm', 80, 'TV host & creator',
    "Saudi presenter of the inspirational self-improvement show 'Khawater'",
    'inspiring, thoughtful, optimistic',
    { l: 'short/beard/ghutra', c: ['#00bfa5', '#ffffff'], a: ['Shugairi', 'الشقيري', 'Khawater'], env: 'podcast', en: 'warm', langs: ['ar', 'en'] }),
  p('anas-bukhash', 'Anas Bukhash', 'أنس بوخش', 'AE', 'm', 76, 'Podcaster',
    'Emirati host of the candid interview show #ABtalks',
    'empathetic, curious, deep questions',
    { l: 'short/beard/none/jacket', c: ['#212121', '#d4af37'], a: ['Anas', 'ABtalks', 'أنس'], env: 'podcast', en: 'calm', langs: ['ar', 'en'] }),
  p('airrack', 'Airrack', 'إيراك', 'US', 'm', 70, 'YouTuber',
    'Challenge YouTuber known for outrageous stunts and records',
    'hyper, optimistic, goofy',
    { l: 'short:light/none/none/hoodie', c: ['#ffea00', '#ff1744'], a: ['Eric', 'Airrack'], d: '2026-09-30' }),
]);

export const gaming = category('gaming', [
  p('faker', 'Faker', 'فيكر', 'KR', 'm', 86, 'League of Legends',
    'Record-holding League of Legends world champion and esports’ greatest player',
    'humble, calm, philosophical, bookish',
    { l: 'short/none/glasses/hoodie', c: ['#e2012d', '#000000'], a: ['Lee Sang-hyeok', 'The Unkillable Demon King', 'Faker'], en: 'calm', langs: ['ko', 'en'] }),
  p('s1mple', 's1mple', 'سيمبل', 'UA', 'm', 76, 'Counter-Strike',
    'Ukrainian Counter-Strike legend widely called the greatest CS player',
    'confident, emotional, sharp',
    { l: 'short/stubble/headphones/hoodie', c: ['#ffd600', '#0057b7'], a: ['Simple', 'Sasha'], langs: ['ru', 'uk', 'en'] }),
  p('shroud', 'shroud', 'شراود', 'CA', 'm', 78, 'FPS streamer',
    'Former Counter-Strike pro turned FPS streaming icon',
    'chill, dry humour, precise aim',
    { l: 'short/stubble/headphones/hoodie', c: ['#00e5ff', '#212121'], a: ['Shroud', 'Mike'], en: 'calm' }),
  p('tenz', 'TenZ', 'تينز', 'CA', 'm', 72, 'Valorant',
    'Valorant star and Masters champion',
    'friendly, cracked aim, tinkerer',
    { l: 'short:light/none/headphones/hoodie', c: ['#ff4655', '#0f1923'], a: ['Tyson', 'TenZ'], en: 'warm' }),
  p('bugha', 'Bugha', 'بوغا', 'US', 'm', 70, 'Fortnite',
    'Inaugural Fortnite World Cup solo champion',
    'competitive, focused, quiet',
    { l: 'short/none/headphones/hoodie', c: ['#7c4dff', '#00e5ff'], a: ['Kyle', 'Bugha'], en: 'calm' }),
  p('msdossary', 'MSDossary', 'مساعد الدوسري', 'SA', 'm', 76, 'Football esports',
    'Saudi FIFA eWorld Cup champion',
    'focused, confident, proud',
    { l: 'short/beard/headphones/hoodie', c: ['#006c35', '#00e5ff'], a: ['Mosaad Aldossary', 'مساعد', 'MSDossary7'], langs: ['ar', 'en'] }),
  p('valkyrae', 'Valkyrae', 'فالكيري', 'US', 'f', 72, 'Streamer',
    'Gaming streamer and 100 Thieves co-owner',
    'bubbly, honest, gamer',
    { l: 'long/none/headphones/hoodie', c: ['#ff1744', '#ffd600'], a: ['Rae'], en: 'warm' }),
  p('hikaru-nakamura', 'Hikaru Nakamura', 'هيكارو ناكامورا', 'US', 'm', 78, 'Chess streamer',
    "Chess grandmaster and the game's biggest streamer",
    'fast-thinking, playful, trash-talking',
    { l: 'short/stubble/none/hoodie', c: ['#7cb342', '#212121'], a: ['Hikaru', 'GMHikaru'], env: 'hall' }),
  p('magnus-carlsen', 'Magnus Carlsen', 'ماغنوس كارلسن', 'NO', 'm', 84, 'Chess',
    'Five-time world chess champion and the highest-rated player in history',
    'confident, playful, football-loving',
    { l: 'short:light/stubble/none/suit', c: ['#ba0c2f', '#00205b'], a: ['Magnus', 'Carlsen'], env: 'hall', en: 'calm', langs: ['no', 'en'] }),
  p('daigo-umehara', 'Daigo Umehara', 'دايغو أوميهارا', 'JP', 'm', 70, 'Fighting games',
    "Street Fighter legend behind the famous 'Evo Moment 37'",
    'humble, philosophical, dedicated',
    { l: 'short/none/none/hoodie', e: 'legend', c: ['#ffd600', '#d50000'], a: ['The Beast', 'Daigo'], en: 'calm', langs: ['ja', 'en'] }),
  p('ludwig', 'Ludwig', 'لودفيغ', 'US', 'm', 72, 'Streamer',
    'Chaotic variety streamer and esports event organiser',
    'nerdy, self-deprecating, inventive',
    { l: 'short:light/none/none/hoodie', c: ['#00c853', '#ffd600'], a: ['Ludwig Ahgren'] }),
]);
