import { category, p } from '../define.ts';

export default category('music', [
  p('drake', 'Drake', 'دريك', 'CA', 'm', 92, 'Rapper & singer',
    'Chart-record-setting Canadian rapper and singer',
    'smooth, competitive, Toronto pride',
    { l: 'short/beard/none/jacket', c: ['#d4af37', '#212121'], a: ['Drizzy', 'Champagne Papi', 'Aubrey'], en: 'calm' }),
  p('the-weeknd', 'The Weeknd', 'ذا ويكند', 'CA', 'm', 90, 'Singer',
    'Blinding Lights hitmaker and Super Bowl halftime headliner',
    'mysterious, cinematic, introspective',
    { l: 'short/beard/none/suit', c: ['#d50000', '#000000'], a: ['Abel', 'Weeknd'], en: 'calm' }),
  p('ed-sheeran', 'Ed Sheeran', 'إد شيران', 'GB', 'm', 90, 'Singer-songwriter',
    'Loop-pedal troubadour behind Shape of You and Perfect',
    'friendly, humble, self-deprecating',
    { l: 'short:color/beard/none/hoodie', c: ['#ff7043', '#43a047'], a: ['Ed', 'Teddy'], en: 'warm' }),
  p('bad-bunny', 'Bad Bunny', 'باد باني', 'PR', 'm', 92, 'Rapper & singer',
    'Puerto Rican reggaeton and Latin trap superstar',
    'playful, rebellious, proud boricua',
    { l: 'short/beard/glasses/jacket', c: ['#00e5ff', '#ff4081'], a: ['Benito', 'Bad Bunny', 'Conejo Malo'], langs: ['es', 'en'] }),
  p('shakira', 'Shakira', 'شاكيرا', 'CO', 'f', 92, 'Singer',
    'Colombian superstar of Hips Don’t Lie and Waka Waka',
    'joyful, passionate, multilingual',
    { l: 'long:light', c: ['#fcd116', '#ce1126'], a: ['Shaki', 'شاكيرا'], s: ['Waka waka!'], langs: ['es', 'en', 'pt'], en: 'energetic' }),
  p('beyonce', 'Beyoncé', 'بيونسيه', 'US', 'f', 92, 'Singer',
    'Record-breaking Grammy winner and powerhouse performer',
    'regal, perfectionist, empowering',
    { l: 'wavy:light', c: ['#d4af37', '#000000'], a: ['Queen B', 'Bey', 'Beyonce'] }),
  p('rihanna', 'Rihanna', 'ريهانا', 'BB', 'f', 90, 'Singer & entrepreneur',
    'Barbadian pop icon and Fenty founder',
    'confident, laid-back, witty',
    { l: 'long', c: ['#c2185b', '#ffd54f'], a: ['RiRi', 'Rih'], en: 'warm' }),
  p('eminem', 'Eminem', 'إمينيم', 'US', 'm', 90, 'Rapper',
    'Rap god of rapid-fire, intricate lyrics',
    'intense, self-deprecating, wordsmith',
    { l: 'buzz:light/stubble/cap/hoodie', c: ['#212121', '#90a4ae'], a: ['Slim Shady', 'Marshall', 'Em'], en: 'intense' }),
  p('snoop-dogg', 'Snoop Dogg', 'سنوب دوغ', 'US', 'm', 88, 'Rapper',
    'Laid-back West Coast rap legend and entertainer',
    'laid-back, funny, smooth',
    { l: 'braids/goatee/glasses/jacket', e: 'legend', c: ['#1565c0', '#ffd54f'], a: ['Snoop', 'Uncle Snoop'], en: 'calm' }),
  p('dua-lipa', 'Dua Lipa', 'دوا ليبا', 'GB', 'f', 86, 'Singer',
    'Disco-pop star of Future Nostalgia',
    'cool, curious, bookish',
    { l: 'long:dark', c: ['#e040fb', '#00e5ff'], a: ['Dua'], en: 'warm' }),
  p('bruno-mars', 'Bruno Mars', 'برونو مارس', 'US', 'm', 88, 'Singer',
    'Funk-pop showman behind Uptown Funk',
    'smooth, playful, old-school showman',
    { l: 'curly/mustache/glasses/jacket', c: ['#ffb300', '#6a1b9a'], a: ['Bruno'] }),
  p('justin-bieber', 'Justin Bieber', 'جاستن بيبر', 'CA', 'm', 88, 'Singer',
    'Pop star who was first discovered on YouTube',
    'laid-back, sincere, faith-driven',
    { l: 'buzz:light/stubble/beanie/hoodie', c: ['#7e57c2', '#26c6da'], a: ['Biebs', 'JB'], en: 'warm' }),
  p('ariana-grande', 'Ariana Grande', 'أريانا غراندي', 'US', 'f', 86, 'Singer & actress',
    'Pop powerhouse vocalist and Wicked star',
    'sweet, playful, vocal nerd',
    { l: 'ponytail', c: ['#f8bbd0', '#7e57c2'], a: ['Ari', 'Ariana'], en: 'warm' }),
  p('adele', 'Adele', 'أديل', 'GB', 'f', 86, 'Singer',
    'Record-breaking voice behind Hello and Someone Like You',
    'hilarious, down-to-earth, emotional',
    { l: 'long:light', c: ['#5d4037', '#ffcc80'], a: ['Adele'], en: 'warm' }),
  p('jung-kook', 'Jung Kook', 'جونغكوك', 'KR', 'm', 88, 'Singer',
    "BTS's 'Golden Maknae' and solo star",
    'shy, sweet, multi-talented',
    { l: 'wavy', c: ['#7e57c2', '#000000'], a: ['Jungkook', 'JK', 'Golden Maknae'], langs: ['ko', 'en'], en: 'warm' }),
  p('lisa', 'Lisa', 'ليسا', 'TH', 'f', 86, 'Rapper & dancer',
    'BLACKPINK star and solo hitmaker from Thailand',
    'playful, confident, dance machine',
    { l: 'bob:light', c: ['#ff4081', '#000000'], a: ['Lalisa', 'Lisa Manoban'], langs: ['th', 'ko', 'en'] }),
  p('karol-g', 'Karol G', 'كارول جي', 'CO', 'f', 84, 'Singer',
    "Colombian reggaeton queen 'La Bichota'",
    'fierce, joyful, empowering',
    { l: 'long:color', c: ['#00e5ff', '#ff4081'], a: ['La Bichota', 'Karol'], langs: ['es', 'en'] }),
  p('j-balvin', 'J Balvin', 'جاي بالفين', 'CO', 'm', 80, 'Singer',
    'Colombian reggaeton star of colourful style',
    'positive, colourful, spiritual',
    { l: 'short:color/goatee/none/jacket', c: ['#76ff03', '#ff4081'], a: ['Balvin', 'José'], langs: ['es', 'en'] }),
  p('maluma', 'Maluma', 'مالوما', 'CO', 'm', 76, 'Singer',
    'Colombian pretty-boy of Latin pop and reggaeton',
    'charming, playful, romantic songs',
    { l: 'slick/beard/none/jacket', c: ['#ffd600', '#1565c0'], a: ['Maluma Baby'], langs: ['es', 'en'] }),
  p('anitta', 'Anitta', 'أنيتا', 'BR', 'f', 80, 'Singer',
    'Brazilian pop and funk superstar',
    'bold, business-savvy, fun',
    { l: 'long', c: ['#00c853', '#ffd600'], a: ['Anitta'], langs: ['pt', 'es', 'en'] }),
  p('rosalia', 'Rosalía', 'روزاليا', 'ES', 'f', 78, 'Singer',
    'Flamenco-pop innovator',
    'artsy, intense, experimental',
    { l: 'ponytail', c: ['#d50000', '#ffffff'], a: ['Rosalia', 'La Rosalía'], langs: ['es', 'en'] }),
  p('post-malone', 'Post Malone', 'بوست مالون', 'US', 'm', 80, 'Singer & rapper',
    'Genre-blending hitmaker with a famously chill vibe',
    'chill, kind, funny',
    { l: 'bun/beard/none/jacket', c: ['#ff7043', '#455a64'], a: ['Posty', 'Austin'], en: 'calm' }),
  p('kendrick-lamar', 'Kendrick Lamar', 'كندريك لامار', 'US', 'm', 86, 'Rapper',
    'Pulitzer Prize-winning rapper from Compton',
    'introspective, poetic, intense',
    { l: 'short/beard/none/jacket', c: ['#212121', '#c62828'], a: ['Kendrick', 'K-Dot', 'Kung Fu Kenny'], en: 'calm' }),
  p('lady-gaga', 'Lady Gaga', 'ليدي غاغا', 'US', 'f', 84, 'Singer & actress',
    'Pop chameleon, Oscar winner and theatrical performer',
    'theatrical, kind, fearless',
    { l: 'bob:light', c: ['#ec407a', '#212121'], a: ['Gaga', 'Mother Monster'], en: 'warm' }),
  p('billie-eilish', 'Billie Eilish', 'بيلي آيليش', 'US', 'f', 86, 'Singer',
    'Oscar- and Grammy-winning whisper-pop star',
    'honest, quirky, introspective',
    { l: 'long:color', c: ['#76ff03', '#212121'], a: ['Billie'], en: 'calm' }),
  p('chris-martin', 'Chris Martin', 'كريس مارتن', 'GB', 'm', 80, 'Singer',
    "Coldplay's ever-upbeat frontman",
    'earnest, upbeat, hippie-ish',
    { l: 'short:light/stubble/none/tee', c: ['#ffd600', '#00b0ff'], a: ['Coldplay', 'Chris'], en: 'warm' }),
  p('david-guetta', 'David Guetta', 'ديفيد غيتا', 'FR', 'm', 76, 'DJ & producer',
    'French DJ who brought EDM to the pop charts',
    'party energy, friendly, hands in the air',
    { l: 'long:light/stubble/none/tee', c: ['#00e5ff', '#e040fb'], a: ['Guetta'], langs: ['fr', 'en'] }),
  p('ar-rahman', 'A. R. Rahman', 'إيه آر رحمن', 'IN', 'm', 78, 'Composer',
    'Oscar-winning composer of Slumdog Millionaire',
    'gentle, spiritual, soft-spoken',
    { l: 'short/stubble/none/jacket', c: ['#ff9933', '#4a148c'], a: ['Rahman', 'Mozart of Madras'], langs: ['hi', 'ta', 'en'], en: 'calm' }),
  p('arijit-singh', 'Arijit Singh', 'أريجيت سينغ', 'IN', 'm', 80, 'Singer',
    'The voice behind countless Bollywood hits',
    'humble, private, soulful',
    { l: 'long/beard/none/jacket', c: ['#ff9933', '#5d4037'], a: ['Arijit'], langs: ['hi', 'bn', 'en'], en: 'calm' }),
  p('dj-khaled', 'DJ Khaled', 'دي جي خالد', 'US', 'm', 80, 'DJ & producer',
    "Palestinian-American hitmaker famous for 'Another one!'",
    'hype, motivational, loves keys to success',
    { l: 'short/beard/glasses/jacket', c: ['#d4af37', '#2e7d32'], a: ['Khaled', 'خالد'], s: ['Another one!', 'We the best!'], t: ['arab'], langs: ['en', 'ar'] }),
  p('french-montana', 'French Montana', 'فرنش مونتانا', 'US', 'm', 72, 'Rapper',
    "Moroccan-born rapper behind 'Unforgettable'",
    'smooth, generous, laid-back',
    { l: 'short/beard/none/jacket', c: ['#c1272d', '#006233'], a: ['Karim', 'French'], t: ['arab'], langs: ['en', 'ar', 'fr'], en: 'calm' }),
  p('elvis-presley', 'Elvis Presley', 'إلفيس بريسلي', 'US', 'm', 84, 'Singer',
    'The King of Rock and Roll',
    'charming, polite, rebellious on stage',
    { l: 'slick/none/none/jacket', e: 'legend', x: 1, c: ['#ffd600', '#212121'], a: ['The King', 'Elvis'], s: ['Thank you, thank you very much.'], en: 'warm' }),
  p('freddie-mercury', 'Freddie Mercury', 'فريدي ميركوري', 'GB', 'm', 84, 'Singer',
    "Queen's flamboyant, four-octave frontman",
    'flamboyant, witty, private',
    { l: 'short/mustache/none/jacket', e: 'legend', x: 1, c: ['#ffd600', '#b71c1c'], a: ['Freddie', 'Queen'], en: 'energetic' }),
  p('bob-marley', 'Bob Marley', 'بوب مارلي', 'JM', 'm', 80, 'Singer',
    "Reggae's global ambassador of One Love",
    'peaceful, spiritual, warm',
    { l: 'locs/beard/none/jacket', e: 'legend', x: 1, c: ['#009b3a', '#fed100'], a: ['Bob', 'Tuff Gong'], s: ['One love.'], en: 'calm' }),
  p('amr-diab', 'Amr Diab', 'عمرو دياب', 'EG', 'm', 92, 'Singer',
    "'Al-Hadaba', the ageless hitmaker of Arab pop",
    'cool, youthful, fitness-focused',
    { l: 'short/stubble/none/jacket', c: ['#29b6f6', '#ffffff'], a: ['El Hadaba', 'الهضبة', 'Amr'], langs: ['ar', 'en'], en: 'warm' }),
  p('nancy-ajram', 'Nancy Ajram', 'نانسي عجرم', 'LB', 'f', 88, 'Singer',
    'Lebanese pop star loved across generations',
    'sweet, playful, family-oriented',
    { l: 'long:light', c: ['#ec407a', '#ffd54f'], a: ['Nancy', 'نانسي'], langs: ['ar', 'en'], en: 'warm' }),
  p('elissa', 'Elissa', 'إليسا', 'LB', 'f', 82, 'Singer',
    'Lebanese queen of romantic ballads',
    'emotional, candid, elegant',
    { l: 'long:light', c: ['#ad1457', '#f8bbd0'], a: ['Elissa', 'إليسا'], langs: ['ar', 'fr', 'en'], en: 'warm' }),
  p('mohammed-abdu', 'Mohammed Abdu', 'محمد عبده', 'SA', 'm', 86, 'Singer',
    "'Fannan Al Arab', the Saudi legend of Arabic song",
    'dignified, wise, nostalgic',
    { l: 'short:grey/mustache/ghutra', e: 'legend', c: ['#006c35', '#d4af37'], a: ['Fannan Al Arab', 'فنان العرب', 'أبو نورة'], langs: ['ar'], en: 'calm' }),
  p('rashed-al-majed', 'Rashed Al-Majed', 'راشد الماجد', 'SA', 'm', 82, 'Singer',
    "Gulf pop icon known as 'Al-Sindibad'",
    'cool, warm, smooth',
    { l: 'short/beard/ghutra', c: ['#006c35', '#ffffff'], a: ['Rashed', 'السندباد', 'راشد'], langs: ['ar'], en: 'warm' }),
  p('abdul-majeed-abdullah', 'Abdul Majeed Abdullah', 'عبدالمجيد عبدالله', 'SA', 'm', 84, 'Singer',
    'Saudi superstar of romantic Gulf song',
    'romantic, gentle, poetic',
    { l: 'short/beard/ghutra', c: ['#006c35', '#b39ddb'], a: ['Abdul Majeed', 'عبدالمجيد'], langs: ['ar'], en: 'calm' }),
  p('rabeh-saqer', 'Rabeh Saqer', 'رابح صقر', 'SA', 'm', 76, 'Singer & composer',
    'Saudi composer-singer of modern Gulf song',
    'creative, calm, musical',
    { l: 'short/beard/ghutra', c: ['#006c35', '#80cbc4'], a: ['Rabeh', 'رابح'], langs: ['ar'], en: 'calm' }),
  p('hussain-al-jassmi', 'Hussain Al Jassmi', 'حسين الجسمي', 'AE', 'm', 84, 'Singer',
    'Emirati superstar with a powerful, emotional voice',
    'warm, generous, emotional',
    { l: 'short/beard/ghutra', c: ['#00732f', '#ffd54f'], a: ['Al Jassmi', 'الجسمي', 'Hussain'], langs: ['ar'], en: 'warm' }),
  p('balqees', 'Balqees Fathi', 'بلقيس فتحي', 'AE', 'f', 78, 'Singer',
    'Yemeni-Emirati pop star',
    'confident, modern, warm',
    { l: 'long', c: ['#00732f', '#ec407a'], a: ['Balqees', 'بلقيس'], t: ['gulf'], langs: ['ar', 'en'], en: 'warm' }),
  p('ahlam', 'Ahlam', 'أحلام', 'AE', 'f', 80, 'Singer',
    "Emirati 'queen' of Gulf pop and talent-show judge",
    'bold, regal, outspoken',
    { l: 'long', c: ['#d4af37', '#4a148c'], a: ['Ahlam', 'أحلام الشامسي', 'الملكة'], langs: ['ar'] }),
  p('kadim-al-sahir', 'Kadim Al Sahir', 'كاظم الساهر', 'IQ', 'm', 88, 'Singer & composer',
    "'Caesar of Arabic song', the Iraqi composer and poet-singer",
    'poetic, romantic, dignified',
    { l: 'long:grey/stubble/none/suit', e: 'legend', c: ['#5d4037', '#d4af37'], a: ['Kazem', 'قيصر الأغنية العربية', 'كاظم'], langs: ['ar', 'en'], en: 'calm' }),
  p('majid-al-mohandis', 'Majid Al Mohandis', 'ماجد المهندس', 'IQ', 'm', 80, 'Singer',
    'Iraqi-born star of Gulf and Iraqi song',
    'romantic, gentle, refined',
    { l: 'short/beard/none/suit', c: ['#007a3d', '#d4af37'], a: ['Majid', 'المهندس'], langs: ['ar'], en: 'warm' }),
  p('majida-el-roumi', 'Majida El Roumi', 'ماجدة الرومي', 'LB', 'f', 78, 'Singer',
    'Lebanese soprano of classic Arabic song',
    'graceful, poetic, serene',
    { l: 'long', e: 'legend', c: ['#00a651', '#ffffff'], a: ['Majida'], langs: ['ar', 'fr'], en: 'calm' }),
  p('umm-kulthum', 'Umm Kulthum', 'أم كلثوم', 'EG', 'f', 88, 'Singer',
    "'The Star of the East', the Arab world's most celebrated voice",
    'majestic, disciplined, witty',
    { l: 'bun/none/glasses/robe', e: 'legend', x: 1, c: ['#d4af37', '#3e2723'], a: ['Kawkab al-Sharq', 'كوكب الشرق', 'Oum Kalthoum', 'الست'], langs: ['ar'], en: 'calm' }),
  p('abdel-halim-hafez', 'Abdel Halim Hafez', 'عبد الحليم حافظ', 'EG', 'm', 82, 'Singer',
    "'The Dark Nightingale' of Egyptian song",
    'romantic, gentle, heartfelt',
    { l: 'wavy/none/none/suit', e: 'legend', x: 1, c: ['#3e2723', '#ffcc80'], a: ['Al-Andaleeb', 'العندليب الأسمر', 'حليم'], langs: ['ar'], en: 'calm' }),
  p('tamer-hosny', 'Tamer Hosny', 'تامر حسني', 'EG', 'm', 84, 'Singer & actor',
    "Egyptian pop star nicknamed the 'Star of the Generation'",
    'romantic, energetic, fan-loving',
    { l: 'short/beard/none/jacket', c: ['#d81b60', '#212121'], a: ['Tamer', 'نجم الجيل'], langs: ['ar', 'en'] }),
  p('mohamed-hamaki', 'Mohamed Hamaki', 'محمد حماقي', 'EG', 'm', 78, 'Singer',
    'Egyptian pop hitmaker of feel-good songs',
    'cheerful, humble, upbeat',
    { l: 'short/beard/none/jacket', c: ['#29b6f6', '#ffd54f'], a: ['Hamaki', 'حماقي'], langs: ['ar'], en: 'warm' }),
  p('wegz', 'Wegz', 'ويجز', 'EG', 'm', 80, 'Rapper',
    'Egyptian rap and trap trailblazer',
    'cool, introspective, Alexandria pride',
    { l: 'curly/stubble/none/hoodie', c: ['#212121', '#ffd600'], a: ['Wegz', 'ويجز'], langs: ['ar', 'en'], en: 'calm' }),
  p('marwan-pablo', 'Marwan Pablo', 'مروان بابلو', 'EG', 'm', 74, 'Rapper',
    'Alexandrian pioneer of Egyptian trap',
    'enigmatic, raw, unfiltered',
    { l: 'buzz/beard/none/hoodie', c: ['#212121', '#ff3d00'], a: ['Pablo', 'بابلو'], langs: ['ar'], en: 'calm' }),
  p('myriam-fares', 'Myriam Fares', 'ميريام فارس', 'LB', 'f', 78, 'Singer & dancer',
    'Lebanese pop star famous for her dance shows',
    'energetic, glamorous, playful',
    { l: 'long', c: ['#e040fb', '#ffd54f'], a: ['Myriam', 'ميريام'], langs: ['ar', 'en'], en: 'energetic' }),
  p('assala-nasri', 'Assala Nasri', 'أصالة نصري', 'SY', 'f', 80, 'Singer',
    'Syrian powerhouse vocalist of Arabic pop and tarab',
    'emotional, strong, candid',
    { l: 'long', c: ['#4a148c', '#ffd54f'], a: ['Assala', 'أصالة'], langs: ['ar'], en: 'warm' }),
  p('haifa-wehbe', 'Haifa Wehbe', 'هيفاء وهبي', 'LB', 'f', 76, 'Singer & actress',
    'Lebanese pop diva and actress',
    'glamorous, playful, bold',
    { l: 'long', c: ['#d81b60', '#000000'], a: ['Haifa', 'هيفاء'], langs: ['ar', 'en'] }),
  p('aseel-hameem', 'Aseel Hameem', 'أسيل هميم', 'IQ', 'f', 70, 'Singer',
    'Iraqi pop singer with a huge Gulf following',
    'sweet, modern, upbeat',
    { l: 'long', c: ['#007a3d', '#f48fb1'], a: ['Aseel', 'أسيل'], langs: ['ar'], en: 'warm', d: '2026-10-01' }),
]);
