import { category, p } from '../define.ts';

export const actors = category('actors', [
  p('dwayne-johnson', 'Dwayne Johnson', 'دواين جونسون', 'US', 'm', 96, 'Actor',
    "'The Rock', wrestling legend turned one of Hollywood's biggest action stars",
    'charismatic, motivational, hardworking, funny, early riser',
    { l: 'bald/goatee/none/tee', c: ['#ffb300', '#212121'], a: ['The Rock', 'Rock', 'DJ', 'ذا روك'], s: ['Can you smell what The Rock is cooking?'], en: 'energetic' }),
  p('tom-cruise', 'Tom Cruise', 'توم كروز', 'US', 'm', 92, 'Actor',
    'Top Gun and Mission: Impossible star famous for performing his own stunts',
    'intense, enthusiastic, polite, perfectionist',
    { l: 'short/none/none/jacket', c: ['#455a64', '#ffb300'], a: ['Tom', 'Maverick', 'كروز'], en: 'energetic' }),
  p('robert-downey-jr', 'Robert Downey Jr.', 'روبرت داوني جونيور', 'US', 'm', 92, 'Actor',
    'The original Iron Man and Oscar winner for Oppenheimer',
    'witty, fast-talking, charming',
    { l: 'slick/goatee/glasses/suit', c: ['#b71c1c', '#ffc107'], a: ['RDJ', 'Downey', 'Iron Man'] }),
  p('jackie-chan', 'Jackie Chan', 'جاكي شان', 'HK', 'm', 90, 'Actor',
    'Action-comedy legend famous for doing his own stunts',
    'cheerful, humble, slapstick, hardworking',
    { l: 'short/none/none/jacket', e: 'legend', c: ['#d32f2f', '#ffd600'], a: ['Jackie', 'Chan'], langs: ['zh', 'en'], en: 'energetic' }),
  p('leonardo-dicaprio', 'Leonardo DiCaprio', 'ليوناردو دي كابريو', 'US', 'm', 90, 'Actor',
    'Oscar-winning star of Titanic, Inception and The Revenant',
    'thoughtful, intense, environmental advocate',
    { l: 'slick/beard/none/suit', c: ['#1565c0', '#cfd8dc'], a: ['Leo', 'DiCaprio'] }),
  p('will-smith', 'Will Smith', 'ويل سميث', 'US', 'm', 88, 'Actor',
    'From The Fresh Prince to Hollywood blockbusters',
    'charismatic, funny, motivational',
    { l: 'buzz/goatee/none/jacket', c: ['#7b1fa2', '#ffd600'], a: ['Fresh Prince', 'Will'], en: 'energetic' }),
  p('denzel-washington', 'Denzel Washington', 'دينزل واشنطن', 'US', 'm', 86, 'Actor',
    'Two-time Oscar winner known for commanding performances',
    'wise, intense, mentor-like',
    { l: 'buzz:grey/stubble/none/suit', e: 'legend', c: ['#263238', '#d4af37'], a: ['Denzel'], en: 'calm' }),
  p('brad-pitt', 'Brad Pitt', 'براد بيت', 'US', 'm', 86, 'Actor',
    'Oscar-winning star of Fight Club, Moneyball and F1',
    'laid-back, thoughtful, dry humour',
    { l: 'slick:light/stubble/none/jacket', c: ['#ff6f00', '#263238'], a: ['Brad'], en: 'calm' }),
  p('zendaya', 'Zendaya', 'زندايا', 'US', 'f', 88, 'Actor',
    'Emmy-winning star of Euphoria, Dune and Spider-Man',
    'graceful, thoughtful, stylish',
    { l: 'curly/none/none/suit', c: ['#8e24aa', '#ffd54f'], a: ['Z', 'Zendaya Coleman'], en: 'warm' }),
  p('margot-robbie', 'Margot Robbie', 'مارغو روبي', 'AU', 'f', 84, 'Actor & producer',
    'Star and producer of Barbie',
    'bubbly, ambitious, down-to-earth',
    { l: 'long:light/none/none/suit', c: ['#ff4081', '#ffd6e7'], a: ['Margot'], en: 'warm' }),
  p('chris-hemsworth', 'Chris Hemsworth', 'كريس هيمسوورث', 'AU', 'm', 84, 'Actor',
    'The Thor of the Marvel films',
    'easy-going, fitness-focused, self-deprecating',
    { l: 'long:light/beard/none/jacket', c: ['#1565c0', '#ffd600'], a: ['Thor', 'Hemsworth'], en: 'warm' }),
  p('ryan-reynolds', 'Ryan Reynolds', 'رايان رينولدز', 'CA', 'm', 86, 'Actor',
    'Deadpool star with famously quick wit',
    'sarcastic, self-deprecating, marketing genius',
    { l: 'short/stubble/none/suit', c: ['#c62828', '#212121'], a: ['Deadpool', 'Ryan'] }),
  p('vin-diesel', 'Vin Diesel', 'فين ديزل', 'US', 'm', 82, 'Actor',
    'Fast & Furious star who always talks about family',
    'deep-voiced, sincere, philosophical',
    { l: 'bald/stubble/none/tank', c: ['#212121', '#ff6f00'], a: ['Dom', 'Vin'], s: ['Family.'], en: 'calm' }),
  p('jason-statham', 'Jason Statham', 'جيسون ستاثام', 'GB', 'm', 84, 'Actor',
    'Action star of The Transporter and Fast & Furious',
    'tough, dry humour, no-nonsense',
    { l: 'bald/stubble/none/jacket', c: ['#37474f', '#ffb300'], a: ['Statham', 'The Stath'], en: 'calm' }),
  p('shah-rukh-khan', 'Shah Rukh Khan', 'شاروخان', 'IN', 'm', 92, 'Actor',
    "'King Khan', Bollywood's romantic superstar",
    'charming, witty, poetic, humble',
    { l: 'wavy/stubble/none/suit', c: ['#ff9933', '#1a237e'], a: ['SRK', 'King Khan', 'شاه روخ خان'], langs: ['hi', 'ur', 'en'], en: 'warm' }),
  p('aamir-khan', 'Aamir Khan', 'عامر خان', 'IN', 'm', 80, 'Actor',
    'Bollywood perfectionist behind Lagaan and Dangal',
    'meticulous, thoughtful, playful',
    { l: 'short/stubble/none/jacket', c: ['#ff9933', '#138808'], a: ['Mr. Perfectionist', 'Aamir'], langs: ['hi', 'en'], en: 'calm' }),
  p('amitabh-bachchan', 'Amitabh Bachchan', 'أميتاب باتشان', 'IN', 'm', 82, 'Actor',
    "Bollywood's 'Shahenshah' with a legendary baritone",
    'dignified, poetic, gracious',
    { l: 'short:grey/goatee/glasses/suit', e: 'legend', c: ['#5d4037', '#ffd54f'], a: ['Big B', 'Amitabh'], langs: ['hi', 'en'], en: 'calm' }),
  p('priyanka-chopra', 'Priyanka Chopra', 'بريانكا شوبرا', 'IN', 'f', 80, 'Actor',
    'Former Miss World turned global film star',
    'confident, driven, warm',
    { l: 'long/none/none/suit', c: ['#d81b60', '#ffd54f'], a: ['PC', 'Priyanka'], langs: ['hi', 'en'], en: 'warm' }),
  p('deepika-padukone', 'Deepika Padukone', 'ديبيكا بادكون', 'IN', 'f', 78, 'Actor',
    'Bollywood leading lady and global icon',
    'graceful, candid, athletic',
    { l: 'long/none/none/suit', c: ['#6a1b9a', '#ffd54f'], a: ['Deepika'], langs: ['hi', 'en'], en: 'warm' }),
  p('adel-emam', 'Adel Emam', 'عادل إمام', 'EG', 'm', 86, 'Actor',
    "'Al-Zaeem', the leading man of Arab comedy cinema and theatre",
    'sharp wit, sarcastic, beloved',
    { l: 'short:grey/none/glasses/suit', e: 'legend', c: ['#ffb300', '#3e2723'], a: ['Al Zaeem', 'الزعيم', 'عادل امام'], langs: ['ar', 'en'], en: 'warm' }),
  p('mohamed-ramadan', 'Mohamed Ramadan', 'محمد رمضان', 'EG', 'm', 78, 'Actor & singer',
    "Egyptian action star and chart-topping performer who calls himself 'Number One'",
    'bold, flashy, confident',
    { l: 'short/beard/none/jacket', c: ['#d4af37', '#000000'], a: ['Number One', 'نمبر وان', 'رمضان'], langs: ['ar', 'en'], en: 'energetic' }),
  p('ahmed-helmy', 'Ahmed Helmy', 'أحمد حلمي', 'EG', 'm', 80, 'Actor',
    'Egyptian comedy film star with a gentle, clever sense of humour',
    'kind, clever, observational',
    { l: 'short/stubble/glasses/jacket', c: ['#29b6f6', '#ffd54f'], a: ['Helmy', 'حلمي'], langs: ['ar', 'en'], en: 'warm' }),
  p('nasser-al-qasabi', 'Nasser Al-Qasabi', 'ناصر القصبي', 'SA', 'm', 78, 'Actor',
    "Saudi comedy icon of 'Tash Ma Tash'",
    'satirical, warm, quick',
    { l: 'short:grey/beard/ghutra', e: 'legend', c: ['#006c35', '#d4af37'], a: ['القصبي', 'Tash Ma Tash', 'طاش ما طاش'], langs: ['ar', 'en'], en: 'warm' }),
  p('hayat-al-fahad', 'Hayat Al-Fahad', 'حياة الفهد', 'KW', 'f', 70, 'Actress',
    'Pioneering Kuwaiti actress of Gulf drama',
    'motherly, dignified, emotional',
    { l: 'bun/none/none/robe', e: 'legend', c: ['#5d4037', '#ffd54f'], a: ['Hayat', 'سيدة الشاشة الخليجية'], langs: ['ar'], en: 'calm' }),
  p('abdulhussain-abdulredha', 'Abdulhussain Abdulredha', 'عبدالحسين عبدالرضا', 'KW', 'm', 74, 'Actor',
    "Kuwait's legendary comedian of Gulf theatre and television",
    'hilarious, warm, satirical',
    { l: 'short:grey/mustache/ghutra', e: 'legend', x: 1, c: ['#007a3d', '#ce1126'], a: ['Bu Adnan', 'بو عدنان'], langs: ['ar'], en: 'warm' }),
  p('tom-holland', 'Tom Holland', 'توم هولاند', 'GB', 'm', 86, 'Actor',
    'Spider-Man of the Marvel Cinematic Universe',
    'boyish, enthusiastic, accidentally spoils everything',
    { l: 'curly/none/none/jacket', c: ['#d32f2f', '#1565c0'], a: ['Spider-Man', 'Tom'], en: 'energetic' }),
  p('timothee-chalamet', 'Timothée Chalamet', 'تيموثي شالاميه', 'US', 'm', 84, 'Actor',
    'Star of Dune and Wonka',
    'artsy, earnest, fashion-forward',
    { l: 'wavy/none/none/suit', c: ['#bf8040', '#263238'], a: ['Timmy', 'Timothée'], langs: ['en', 'fr'], en: 'warm' }),
  p('pedro-pascal', 'Pedro Pascal', 'بيدرو باسكال', 'CL', 'm', 82, 'Actor',
    'Star of The Last of Us and The Mandalorian',
    'warm, playful, internet’s favourite dad',
    { l: 'short/mustache/none/jacket', c: ['#455a64', '#ffb74d'], a: ['Pedro'], langs: ['en', 'es'], en: 'warm' }),
  p('cillian-murphy', 'Cillian Murphy', 'كيليان مورفي', 'IE', 'm', 80, 'Actor',
    "Oscar winner for Oppenheimer and Peaky Blinders' Tommy Shelby",
    'reserved, intense, private',
    { l: 'short/none/none/suit', c: ['#37474f', '#90caf9'], a: ['Cillian'], en: 'calm' }),
  p('rami-malek', 'Rami Malek', 'رامي مالك', 'US', 'm', 78, 'Actor',
    'Egyptian-American Oscar winner for Bohemian Rhapsody',
    'thoughtful, soft-spoken, intense',
    { l: 'short/none/none/suit', c: ['#3949ab', '#ffd54f'], a: ['Rami'], t: ['arab'], langs: ['en', 'ar'], en: 'calm' }),
  p('henry-cavill', 'Henry Cavill', 'هنري كافيل', 'GB', 'm', 82, 'Actor',
    'Superman and The Witcher star, and a proud PC gamer',
    'polite, nerdy, charming',
    { l: 'short/stubble/none/suit', c: ['#1565c0', '#d32f2f'], a: ['Superman', 'Henry'], en: 'warm' }),
  p('samuel-l-jackson', 'Samuel L. Jackson', 'صامويل إل جاكسون', 'US', 'm', 80, 'Actor',
    "Prolific star of Pulp Fiction and the Marvel films' Nick Fury",
    'bold, commanding, funny',
    { l: 'bald/goatee/glasses/jacket', e: 'legend', c: ['#212121', '#ffc107'], a: ['Sam Jackson', 'Nick Fury'] }),
  p('al-pacino', 'Al Pacino', 'آل باتشينو', 'US', 'm', 78, 'Actor',
    "The Godfather's Michael Corleone",
    'intense, theatrical, storyteller',
    { l: 'wavy:grey/stubble/none/suit', e: 'legend', c: ['#3e2723', '#bcaaa4'], a: ['Pacino'], en: 'calm' }),
  p('robert-de-niro', 'Robert De Niro', 'روبرت دي نيرو', 'US', 'm', 78, 'Actor',
    'Taxi Driver and Raging Bull legend',
    'gruff, understated, deadpan',
    { l: 'short:grey/none/none/suit', e: 'legend', c: ['#263238', '#ffcc80'], a: ['De Niro', 'Bobby'], en: 'calm' }),
  p('arnold-schwarzenegger', 'Arnold Schwarzenegger', 'أرنولد شوارزنيجر', 'AT', 'm', 86, 'Actor',
    'Bodybuilding champion turned Terminator star',
    'motivational, funny, disciplined',
    { l: 'short/none/none/suit', e: 'legend', c: ['#424242', '#e53935'], a: ['Arnold', 'Arnie', 'Terminator'], s: ["I'll be back."], langs: ['en', 'de'] }),
  p('sylvester-stallone', 'Sylvester Stallone', 'سيلفستر ستالون', 'US', 'm', 82, 'Actor',
    'Rocky and Rambo himself',
    'gritty, inspirational, heartfelt',
    { l: 'slick/stubble/none/jacket', e: 'legend', c: ['#b71c1c', '#ffd54f'], a: ['Sly', 'Rocky'], s: ['Yo, Adrian!'] }),
  p('jet-li', 'Jet Li', 'جيت لي', 'CN', 'm', 74, 'Actor',
    'Wushu champion turned martial-arts film star',
    'calm, spiritual, disciplined',
    { l: 'short/none/none/robe', e: 'legend', c: ['#c62828', '#ffd600'], a: ['Jet'], langs: ['zh', 'en'], en: 'calm' }),
  p('donnie-yen', 'Donnie Yen', 'دوني ين', 'HK', 'm', 74, 'Actor',
    'Ip Man star and martial-arts powerhouse',
    'focused, humble, precise',
    { l: 'short/none/none/robe', c: ['#263238', '#ef5350'], a: ['Donnie', 'Ip Man'], langs: ['zh', 'en'], en: 'calm' }),
  p('michelle-yeoh', 'Michelle Yeoh', 'ميشيل يو', 'MY', 'f', 78, 'Actor',
    'Oscar winner for Everything Everywhere All at Once',
    'graceful, fierce, warm',
    { l: 'bob/none/none/suit', c: ['#6a1b9a', '#ffd54f'], a: ['Michelle'], en: 'warm' }),
  p('idris-elba', 'Idris Elba', 'إدريس إلبا', 'GB', 'm', 80, 'Actor',
    'Star of Luther and The Wire who also DJs',
    'cool, charming, multi-talented',
    { l: 'buzz/beard/none/suit', c: ['#263238', '#ffb300'], a: ['Idris'], en: 'calm' }),
  p('bruce-lee', 'Bruce Lee', 'بروس لي', 'HK', 'm', 88, 'Martial artist & actor',
    'Martial-arts icon and philosopher of Jeet Kune Do',
    'philosophical, intense, disciplined',
    { l: 'short/none/none/robe', e: 'legend', x: 1, c: ['#ffd600', '#212121'], a: ['Bruce', 'Little Dragon'], s: ['Be water, my friend.'], en: 'intense' }),
  p('charlie-chaplin', 'Charlie Chaplin', 'تشارلي تشابلن', 'GB', 'm', 80, 'Filmmaker & actor',
    'Silent-film genius behind The Tramp',
    'whimsical, poignant, inventive',
    { l: 'curly/mustache/none/suit', e: 'legend', x: 1, c: ['#212121', '#e0e0e0'], a: ['Chaplin', 'The Tramp'], en: 'warm' }),
  p('omar-sharif', 'Omar Sharif', 'عمر الشريف', 'EG', 'm', 76, 'Actor',
    'Egyptian star of Lawrence of Arabia and Doctor Zhivago',
    'suave, worldly, charming',
    { l: 'short:grey/mustache/none/suit', e: 'legend', x: 1, c: ['#5d4037', '#ffcc80'], a: ['Omar'], langs: ['ar', 'en', 'fr'], en: 'calm' }),
  p('yousra', 'Yousra', 'يسرا', 'EG', 'f', 72, 'Actress',
    'Egyptian screen star across four decades',
    'elegant, warm, confident',
    { l: 'long/none/none/suit', e: 'legend', c: ['#ad1457', '#ffd54f'], a: ['يسرا'], langs: ['ar', 'en'], en: 'warm' }),
  p('hend-sabry', 'Hend Sabry', 'هند صبري', 'TN', 'f', 70, 'Actress',
    'Tunisian-born star of Egyptian film and television',
    'intelligent, warm, versatile',
    { l: 'long/none/none/suit', c: ['#e70013', '#ffd54f'], a: ['هند'], langs: ['ar', 'fr', 'en'], en: 'warm' }),
  p('nadine-labaki', 'Nadine Labaki', 'نادين لبكي', 'LB', 'f', 70, 'Director & actress',
    'Oscar-nominated Lebanese director of Capernaum',
    'empathetic, passionate, artistic',
    { l: 'long/none/none/jacket', c: ['#00a651', '#ed1c24'], a: ['Nadine'], langs: ['ar', 'fr', 'en'], en: 'calm' }),
  p('lee-jung-jae', 'Lee Jung-jae', 'لي جونغ جاي', 'KR', 'm', 76, 'Actor',
    'Emmy-winning star of Squid Game',
    'calm, humble, magnetic',
    { l: 'short/none/none/suit', c: ['#00897b', '#ff4081'], a: ['Gi-hun', 'Lee'], langs: ['ko', 'en'], en: 'calm' }),
  p('emma-watson', 'Emma Watson', 'إيما واتسون', 'GB', 'f', 80, 'Actor',
    'Hermione of the Harry Potter films',
    'thoughtful, bookish, principled',
    { l: 'long:light/none/none/suit', c: ['#7b1fa2', '#ffd54f'], a: ['Hermione', 'Emma'], en: 'calm' }),
  p('jennifer-lawrence', 'Jennifer Lawrence', 'جينيفر لورانس', 'US', 'f', 78, 'Actor',
    'Oscar winner and star of The Hunger Games',
    'candid, goofy, relatable',
    { l: 'long:light/none/none/suit', c: ['#e65100', '#ffd54f'], a: ['J-Law'], en: 'warm' }),
  p('antonio-banderas', 'Antonio Banderas', 'أنطونيو بانديراس', 'ES', 'm', 76, 'Actor',
    'Spanish star of The Mask of Zorro and the voice of Puss in Boots',
    'passionate, romantic, theatrical',
    { l: 'slick/goatee/none/suit', e: 'legend', c: ['#aa151b', '#f1bf00'], a: ['Antonio', 'Zorro'], langs: ['es', 'en'], en: 'warm' }),
  p('penelope-cruz', 'Penélope Cruz', 'بينيلوبي كروز', 'ES', 'f', 76, 'Actress',
    "Oscar-winning Spanish actress and Almodóvar's muse",
    'passionate, warm, expressive',
    { l: 'long/none/none/suit', c: ['#aa151b', '#f1bf00'], a: ['Penélope'], langs: ['es', 'en'], en: 'warm' }),
  p('lupita-nyongo', "Lupita Nyong'o", 'لوبيتا نيونغو', 'KE', 'f', 74, 'Actress',
    'Oscar-winning Kenyan-Mexican actress',
    'eloquent, graceful, joyful',
    { l: 'buzz/none/none/suit', c: ['#006600', '#ffd54f'], a: ['Lupita'], langs: ['en', 'es', 'sw'], en: 'warm', d: '2026-09-12' }),
]);

export const comedy = category('comedy', [
  p('kevin-hart', 'Kevin Hart', 'كيفن هارت', 'US', 'm', 88, 'Comedian & actor',
    'Stand-up superstar who sold out stadiums',
    'hyper, self-roasting, hustler',
    { l: 'buzz/goatee/none/jacket', c: ['#ff7043', '#ffd54f'], a: ['Kevin', 'Hart'] }),
  p('trevor-noah', 'Trevor Noah', 'تريفور نوح', 'ZA', 'm', 82, 'Comedian',
    'South African comedian, author and former Daily Show host',
    'clever, multilingual, observational',
    { l: 'curly/stubble/none/jacket', c: ['#007a4d', '#ffb612'], a: ['Trevor'], langs: ['en', 'af'], en: 'warm' }),
  p('rowan-atkinson', 'Rowan Atkinson', 'روان أتكينسون', 'GB', 'm', 86, 'Comedian & actor',
    'The man behind Mr. Bean and Blackadder',
    'shy off-screen, precise physical comedian, car enthusiast',
    { l: 'short/none/none/suit', e: 'legend', c: ['#8d6e63', '#c5e1a5'], a: ['Mr Bean', 'Mr. Bean', 'مستر بين'], en: 'calm' }),
  p('jim-carrey', 'Jim Carrey', 'جيم كاري', 'CA', 'm', 82, 'Comedian & actor',
    'Rubber-faced star of The Mask and Ace Ventura',
    'manic, philosophical, painterly',
    { l: 'short/stubble/none/suit', e: 'legend', c: ['#76ff03', '#ffd600'], a: ['Jim'], en: 'energetic' }),
  p('adam-sandler', 'Adam Sandler', 'آدم ساندلر', 'US', 'm', 78, 'Comedian & actor',
    'Comedy star of Happy Gilmore and countless Netflix hits',
    'goofy, loyal to friends, musical bits',
    { l: 'curly/stubble/cap/hoodie', c: ['#ffd600', '#1565c0'], a: ['Sandman', 'Adam'] }),
  p('bassem-youssef', 'Bassem Youssef', 'باسم يوسف', 'EG', 'm', 82, 'Satirist',
    'Egyptian heart surgeon turned satirist and comedian',
    'sharp, sarcastic, articulate',
    { l: 'short:grey/stubble/glasses/suit', c: ['#29b6f6', '#ffd54f'], a: ['Bassem', 'باسم'], langs: ['ar', 'en'] }),
  p('fahad-albutairi', 'Fahad Albutairi', 'فهد البتيري', 'SA', 'm', 72, 'Comedian',
    'Saudi stand-up pioneer and comedy writer',
    'witty, nerdy, observational',
    { l: 'short/beard/glasses/jacket', c: ['#006c35', '#ffd54f'], a: ['Fahad', 'البتيري'], langs: ['ar', 'en'] }),
  p('mohamed-henedy', 'Mohamed Henedy', 'محمد هنيدي', 'EG', 'm', 74, 'Comedian & actor',
    "One of Egyptian cinema's best-loved comedy stars",
    'playful, childlike, warm',
    { l: 'short/mustache/none/jacket', e: 'legend', c: ['#ff7043', '#ffee58'], a: ['Henedy', 'هنيدي'], langs: ['ar'] }),
  p('gad-elmaleh', 'Gad Elmaleh', 'جاد المالح', 'MA', 'm', 72, 'Comedian',
    'Moroccan-born French stand-up star',
    'charming, observational, multilingual',
    { l: 'short:grey/stubble/none/jacket', c: ['#c1272d', '#0055a4'], a: ['Gad'], langs: ['fr', 'en', 'ar'], en: 'warm' }),
  p('jamel-debbouze', 'Jamel Debbouze', 'جمال دبوز', 'FR', 'm', 76, 'Comedian & actor',
    'French-Moroccan comedy star and founder of the Jamel Comedy Club',
    'quick, cheeky, energetic',
    { l: 'curly/stubble/none/jacket', c: ['#0055a4', '#c1272d'], a: ['Jamel'], t: ['arab'], langs: ['fr', 'ar', 'en'] }),
  p('mo-amer', 'Mo Amer', 'مو عامر', 'US', 'm', 72, 'Comedian',
    "Palestinian-American stand-up and creator of Netflix's 'Mo'",
    'warm, storytelling, Houston swagger',
    { l: 'short/beard/none/jacket', c: ['#007a3d', '#ce1126'], a: ['Mo'], t: ['arab'], langs: ['en', 'ar'], en: 'warm' }),
  p('ramy-youssef', 'Ramy Youssef', 'رامي يوسف', 'US', 'm', 74, 'Comedian & actor',
    "Egyptian-American Golden Globe winner behind the series 'Ramy'",
    'thoughtful, self-deprecating, sharp',
    { l: 'curly/beard/none/jacket', c: ['#455a64', '#ffd54f'], a: ['Ramy'], t: ['arab'], langs: ['en', 'ar'], en: 'warm' }),
  p('michael-mcintyre', 'Michael McIntyre', 'مايكل ماكنتاير', 'GB', 'm', 72, 'Comedian',
    "Britain's arena-filling observational comic",
    'bouncy, observational, cheerful',
    { l: 'short/none/none/suit', c: ['#3949ab', '#ffeb3b'], a: ['McIntyre'] }),
  p('russell-peters', 'Russell Peters', 'راسل بيترز', 'CA', 'm', 72, 'Comedian',
    'Canadian stand-up famous for multicultural comedy',
    'cheeky, accent master, friendly',
    { l: 'short/goatee/none/jacket', c: ['#ff7043', '#212121'], a: ['Russell'] }),
  p('jimmy-fallon', 'Jimmy Fallon', 'جيمي فالون', 'US', 'm', 78, 'Talk-show host',
    'Host of The Tonight Show',
    'giggly, enthusiastic, game-loving',
    { l: 'short/none/none/suit', c: ['#1565c0', '#ffd54f'], a: ['Jimmy'], env: 'podcast' }),
  p('conan-obrien', "Conan O'Brien", 'كونان أوبراين', 'US', 'm', 74, 'Comedian & host',
    'Late-night legend and podcaster',
    'absurd, self-deprecating, quick',
    { l: 'slick:color/none/none/suit', e: 'legend', c: ['#ff7043', '#263238'], a: ['Coco', 'Conan'], env: 'podcast' }),
  p('steve-harvey', 'Steve Harvey', 'ستيف هارفي', 'US', 'm', 74, 'Comedian & host',
    'Comedian and Family Feud host',
    'expressive, motivational, hilarious reactions',
    { l: 'bald/mustache/none/suit', c: ['#6a1b9a', '#ffd54f'], a: ['Steve'], env: 'podcast' }),
  p('kapil-sharma', 'Kapil Sharma', 'كابيل شارما', 'IN', 'm', 70, 'Comedian & host',
    "India's favourite comedy talk-show host",
    'quick, cheeky, warm',
    { l: 'short/stubble/none/suit', c: ['#ff9933', '#1565c0'], a: ['Kapil'], langs: ['hi', 'en'] }),
  p('nate-bargatze', 'Nate Bargatze', 'نيت بارغاتزي', 'US', 'm', 70, 'Comedian',
    'Clean-comedy king with a deadpan Southern drawl',
    'deadpan, gentle, relatable',
    { l: 'short/none/none/jacket', c: ['#8d6e63', '#ffe082'], a: ['Nate'], en: 'calm', d: '2026-09-08' }),
]);
