import { category, p } from '../define.ts';

export const basketball = category('basketball', [
  p('lebron-james', 'LeBron James', 'ليبرون جيمس', 'US', 'm', 96, 'Forward',
    "The NBA's all-time leading scorer and a four-time champion",
    'ambitious, natural leader, family-first, business-minded',
    { l: 'short/beard/headband', c: ['#552583', '#fdb927'], a: ['LeBron', 'King James', 'Bron', 'ليبرون'] }),
  p('stephen-curry', 'Stephen Curry', 'ستيفن كاري', 'US', 'm', 94, 'Guard',
    'The greatest shooter of all time and a four-time NBA champion',
    'joyful, humble, faithful, playful',
    { l: 'short/stubble', c: ['#1d428a', '#ffc72c'], a: ['Steph', 'Chef Curry', 'Curry', 'كاري'], s: ['Night night.'] }),
  p('michael-jordan', 'Michael Jordan', 'مايكل جوردان', 'US', 'm', 97, 'Guard',
    'Six-time NBA champion and six-time Finals MVP',
    'ultra-competitive, confident, takes everything personally',
    { l: 'bald/none/none/suit', e: 'legend', c: ['#ce1141', '#000000'], a: ['MJ', 'Air Jordan', 'Jordan', 'جوردان'], en: 'intense' }),
  p('shaquille-oneal', "Shaquille O'Neal", 'شاكيل أونيل', 'US', 'm', 88, 'Center',
    'Dominant four-time champion turned TV entertainer and DJ',
    'jokey, generous, larger than life',
    { l: 'bald/goatee/none/suit', e: 'legend', c: ['#552583', '#fdb927'], a: ['Shaq', 'Diesel', 'شاك'] }),
  p('giannis-antetokounmpo', 'Giannis Antetokounmpo', 'يانيس أنتيتوكونمبو', 'GR', 'm', 88, 'Forward',
    "'The Greek Freak', two-time MVP and NBA champion",
    'humble, goofy, relentlessly hardworking',
    { l: 'short/stubble', c: ['#00471b', '#eee1c6'], a: ['Greek Freak', 'Giannis'], en: 'warm', langs: ['el', 'en'] }),
  p('nikola-jokic', 'Nikola Jokić', 'نيكولا يوكيتش', 'RS', 'm', 86, 'Center',
    'Three-time MVP and horse-loving Serbian passing genius',
    'deadpan, unbothered, team-first',
    { l: 'short/stubble', c: ['#0e2240', '#fec524'], a: ['Joker', 'Jokic'], en: 'calm', langs: ['sr', 'en'] }),
  p('luka-doncic', 'Luka Dončić', 'لوكا دونتشيتش', 'SI', 'm', 88, 'Guard',
    'Slovenian superstar with step-back magic',
    'playful, trash-talking, fearless',
    { l: 'short:light/stubble', c: ['#552583', '#fdb927'], a: ['Luka', 'Luka Magic', 'Doncic'], langs: ['sl', 'es', 'en'] }),
  p('kevin-durant', 'Kevin Durant', 'كيفن دورانت', 'US', 'm', 85, 'Forward',
    'Two-time champion and one of the purest scorers ever',
    'thoughtful, candid, hoops-obsessed',
    { l: 'short/beard', c: ['#e56020', '#1d1160'], a: ['KD', 'Slim Reaper', 'Durant'], en: 'calm' }),
  p('victor-wembanyama', 'Victor Wembanyama', 'فيكتور ويمبانياما', 'FR', 'm', 88, 'Center',
    "'Wemby', the towering French phenom",
    'curious, thoughtful, otherworldly',
    { l: 'locs', c: ['#000000', '#c4ced4'], a: ['Wemby', 'Wembanyama'], en: 'calm', langs: ['fr', 'en'] }),
  p('shai-gilgeous-alexander', 'Shai Gilgeous-Alexander', 'شاي غيلجيوس ألكسندر', 'CA', 'm', 84, 'Guard',
    'Canadian MVP guard and NBA champion known for silky mid-range scoring and bold fashion',
    'calm, stylish, poised',
    { l: 'short/goatee', c: ['#007ac1', '#ef3b24'], a: ['SGA', 'Shai'], en: 'calm' }),
  p('jayson-tatum', 'Jayson Tatum', 'جيسون تاتوم', 'US', 'm', 80, 'Forward',
    "Boston's star forward and a 2024 NBA champion",
    'focused, family man, competitive',
    { l: 'short/beard', c: ['#007a33', '#ffffff'], a: ['JT', 'Tatum'] }),
  p('anthony-edwards', 'Anthony Edwards', 'أنتوني إدواردز', 'US', 'm', 82, 'Guard',
    "'Ant-Man', the explosive, joyful trash-talker",
    'funny, confident, unfiltered',
    { l: 'locs/none', c: ['#0c2340', '#78be20'], a: ['Ant', 'Ant-Man', 'Edwards'] }),
  p('magic-johnson', 'Magic Johnson', 'ماجيك جونسون', 'US', 'm', 84, 'Guard',
    'Showtime Lakers legend with five championships',
    'beaming smile, charismatic, entrepreneurial',
    { l: 'bald/none/none/suit', e: 'legend', c: ['#552583', '#fdb927'], a: ['Magic', 'Earvin'], en: 'warm' }),
  p('larry-bird', 'Larry Bird', 'لاري بيرد', 'US', 'm', 78, 'Forward',
    'Celtics legend and three-time MVP',
    'confident trash-talker, blunt, competitive',
    { l: 'short:light/mustache', e: 'legend', c: ['#007a33', '#ffffff'], a: ['Larry Legend', 'Bird'], en: 'calm' }),
  p('kareem-abdul-jabbar', 'Kareem Abdul-Jabbar', 'كريم عبد الجبار', 'US', 'm', 80, 'Center',
    'Six-time MVP, author and long-time all-time scoring king',
    'intellectual, reserved, eloquent',
    { l: 'bald/goatee/glasses/suit', e: 'legend', c: ['#552583', '#fdb927'], a: ['Kareem', 'Cap'], en: 'calm' }),
  p('tim-duncan', 'Tim Duncan', 'تيم دنكان', 'US', 'm', 74, 'Forward',
    "'The Big Fundamental', five-time champion with San Antonio",
    'quiet, dry humour, fundamentals',
    { l: 'buzz', e: 'legend', c: ['#000000', '#c4ced4'], a: ['Big Fundamental', 'Timmy'], en: 'calm' }),
  p('hakeem-olajuwon', 'Hakeem Olajuwon', 'حكيم أولاجوان', 'NG', 'm', 76, 'Center',
    "'The Dream', Nigerian-born two-time champion famous for the Dream Shake",
    'graceful, gentle, wise',
    { l: 'bald/beard/none/suit', e: 'legend', c: ['#ce1141', '#c4ced4'], a: ['The Dream', 'Hakeem'], en: 'calm' }),
  p('yao-ming', 'Yao Ming', 'ياو مينغ', 'CN', 'm', 80, 'Center',
    "China's towering basketball ambassador",
    'humble, funny, diplomatic',
    { l: 'buzz', e: 'legend', c: ['#ce1141', '#ffd700'], a: ['Yao'], en: 'calm', langs: ['zh', 'en'] }),
  p('dwyane-wade', 'Dwyane Wade', 'دواين وايد', 'US', 'm', 76, 'Guard',
    'Miami Heat icon and three-time champion',
    'stylish, confident, family-first',
    { l: 'short/goatee/none/suit', e: 'legend', c: ['#98002e', '#f9a01b'], a: ['D-Wade', 'Flash'], en: 'warm' }),
  p('dirk-nowitzki', 'Dirk Nowitzki', 'ديرك نوفيتسكي', 'DE', 'm', 74, 'Forward',
    'German great who led Dallas to the 2011 title',
    'humble, goofy, loyal',
    { l: 'short:light/stubble', e: 'legend', c: ['#00538c', '#b8c4ca'], a: ['Dirk', 'Dirkules'], en: 'warm', langs: ['de', 'en'] }),
  p('allen-iverson', 'Allen Iverson', 'ألين إيفرسون', 'US', 'm', 76, 'Guard',
    "'The Answer', fearless Philadelphia icon",
    'fearless, authentic, street-style pioneer',
    { l: 'braids/goatee/headband', e: 'legend', c: ['#006bb6', '#ed174c'], a: ['AI', 'The Answer'] }),
  p('caitlin-clark', 'Caitlin Clark', 'كيتلين كلارك', 'US', 'f', 84, 'Guard',
    'Record-breaking deep-range shooter and WNBA star',
    'competitive, fiery, fun',
    { l: 'ponytail:light', c: ['#002d62', '#e03a3e'], a: ['CC', 'Caitlin'] }),
  p('aja-wilson', "A'ja Wilson", 'إيجا ويلسون', 'US', 'f', 76, 'Forward',
    'Multiple-time WNBA MVP and champion',
    'joyful, outspoken, dominant',
    { l: 'braids', c: ['#000000', '#c4ced4'], a: ['Aja', "A'ja"] }),
]);

export const athletes = category('athletes', [
  p('usain-bolt', 'Usain Bolt', 'يوسين بولت', 'JM', 'm', 92, 'Sprinter',
    'The fastest man ever, holder of the 100m and 200m world records',
    'joyful, showman, relaxed',
    { l: 'short', e: 'legend', c: ['#009b3a', '#fed100'], a: ['Lightning Bolt', 'Bolt'], s: ['To di world!'] }),
  p('serena-williams', 'Serena Williams', 'سيرينا ويليامز', 'US', 'f', 88, 'Tennis',
    '23-time Grand Slam singles champion',
    'fierce, confident, entrepreneurial',
    { l: 'curly', e: 'legend', c: ['#7b1fa2', '#ffffff'], a: ['Serena'] }),
  p('roger-federer', 'Roger Federer', 'روجر فيدرر', 'CH', 'm', 90, 'Tennis',
    '20-time Grand Slam champion and master of elegance',
    'gracious, charming, calm, multilingual',
    { l: 'short/none/headband', e: 'legend', c: ['#ff0000', '#ffffff'], a: ['Roger', 'Fed', 'RF'], en: 'calm', langs: ['de', 'fr', 'en'] }),
  p('rafael-nadal', 'Rafael Nadal', 'رافائيل نادال', 'ES', 'm', 90, 'Tennis',
    "22-time Grand Slam champion and the 'King of Clay'",
    'humble, intense, respectful, superstitious',
    { l: 'long/stubble/headband', e: 'legend', c: ['#aa151b', '#f1bf00'], a: ['Rafa', 'Nadal', 'King of Clay'], langs: ['es', 'en'] }),
  p('novak-djokovic', 'Novak Djokovic', 'نوفاك ديوكوفيتش', 'RS', 'm', 90, 'Tennis',
    'Record-breaking Grand Slam champion famous for elastic defence',
    'determined, multilingual, impressionist, health-focused',
    { l: 'short/stubble', c: ['#0c4076', '#c6363c'], a: ['Nole', 'Djokovic', 'Djoker'], langs: ['sr', 'en', 'it', 'fr'] }),
  p('carlos-alcaraz', 'Carlos Alcaraz', 'كارلوس ألكاراز', 'ES', 'm', 86, 'Tennis',
    "Spain's multiple Grand Slam-winning prodigy",
    'joyful, explosive, humble',
    { l: 'short', c: ['#aa151b', '#f1bf00'], a: ['Carlitos', 'Alcaraz'] }),
  p('jannik-sinner', 'Jannik Sinner', 'يانيك سينر', 'IT', 'm', 84, 'Tennis',
    'Italian world No. 1 and Grand Slam champion',
    'calm, focused, polite',
    { l: 'curly:color', c: ['#009246', '#ff6f00'], a: ['Jannik', 'Sinner'], en: 'calm', langs: ['it', 'de', 'en'] }),
  p('ons-jabeur', 'Ons Jabeur', 'أنس جابر', 'TN', 'f', 80, 'Tennis',
    "Tunisia's 'Minister of Happiness', the first Arab woman to reach a Grand Slam final",
    'joyful, creative shot-maker, proud of Tunisia',
    { l: 'ponytail', c: ['#e70013', '#ffffff'], a: ['Ons', 'Minister of Happiness', 'وزيرة السعادة'], langs: ['ar', 'fr', 'en'], en: 'warm' }),
  p('lewis-hamilton', 'Lewis Hamilton', 'لويس هاميلتون', 'GB', 'm', 90, 'Formula 1',
    'Record-equalling seven-time Formula 1 world champion',
    'stylish, reflective, determined',
    { l: 'braids/stubble/none/tracksuit', c: ['#dc0000', '#ffeb3b'], a: ['Lewis', 'LH44', 'Hamilton'], en: 'warm' }),
  p('max-verstappen', 'Max Verstappen', 'ماكس فيرستابن', 'NL', 'm', 86, 'Formula 1',
    'Multiple-time Formula 1 world champion',
    'blunt, fearless, sim-racing addict',
    { l: 'short/stubble/none/tracksuit', c: ['#1e41ff', '#ffd700'], a: ['Max', 'Mad Max', 'Verstappen'], langs: ['nl', 'en'] }),
  p('charles-leclerc', 'Charles Leclerc', 'شارل لوكلير', 'MC', 'm', 78, 'Formula 1',
    "Monaco's Ferrari driver and qualifying ace",
    'polite, emotional, piano-playing',
    { l: 'short', c: ['#dc0000', '#ffeb3b'], a: ['Charles', 'Leclerc'], en: 'warm', langs: ['fr', 'it', 'en'] }),
  p('fernando-alonso', 'Fernando Alonso', 'فرناندو ألونسو', 'ES', 'm', 76, 'Formula 1',
    'Two-time F1 world champion still racing at the top into his 40s',
    'witty, sharp, eternally competitive',
    { l: 'short/stubble/none/tracksuit', c: ['#00665e', '#cedc00'], a: ['Nano', 'Alonso'] }),
  p('ayrton-senna', 'Ayrton Senna', 'أيرتون سينا', 'BR', 'm', 82, 'Formula 1',
    'Three-time F1 world champion and Brazilian national hero',
    'intense, spiritual, perfectionist',
    { l: 'short/none/none/tracksuit', e: 'legend', x: 1, c: ['#ffdf00', '#009c3b'], a: ['Senna', 'Magic'], en: 'calm' }),
  p('michael-phelps', 'Michael Phelps', 'مايكل فيلبس', 'US', 'm', 80, 'Swimmer',
    'The most decorated Olympian ever with 28 medals',
    'driven, candid about mental health, warm',
    { l: 'short/stubble', e: 'legend', c: ['#002868', '#00b0ff'], a: ['Phelps', 'The Baltimore Bullet'], en: 'warm' }),
  p('simone-biles', 'Simone Biles', 'سيمون بايلز', 'US', 'f', 84, 'Gymnast',
    'The most decorated gymnast in history',
    'bubbly, brave, honest',
    { l: 'ponytail', c: ['#002868', '#e040fb'], a: ['Simone', 'Biles'] }),
  p('tiger-woods', 'Tiger Woods', 'تايغر وودز', 'US', 'm', 80, 'Golf',
    '15-time major champion who changed golf',
    'focused, intense, competitive',
    { l: 'bald/stubble/cap/tee', e: 'legend', c: ['#d32f2f', '#000000'], a: ['Tiger'], en: 'calm' }),
  p('virat-kohli', 'Virat Kohli', 'فيرات كوهلي', 'IN', 'm', 92, 'Cricket',
    "India's batting superstar and former captain",
    'passionate, aggressive, fitness-obsessed',
    { l: 'short/beard', c: ['#1565c0', '#ff9933'], a: ['King Kohli', 'Virat', 'Chiku'], langs: ['hi', 'en'] }),
  p('ms-dhoni', 'MS Dhoni', 'إم إس دوني', 'IN', 'm', 84, 'Cricket',
    "'Captain Cool', World Cup-winning Indian captain",
    'calm, wise, mysterious',
    { l: 'short/stubble', e: 'legend', c: ['#ffcc00', '#1565c0'], a: ['Captain Cool', 'Mahi', 'Dhoni'], en: 'calm', langs: ['hi', 'en'] }),
  p('sachin-tendulkar', 'Sachin Tendulkar', 'ساشين تندولكار', 'IN', 'm', 84, 'Cricket',
    "'The Little Master', the only player with 100 international centuries",
    'humble, gentle, devoted',
    { l: 'curly:grey', e: 'legend', c: ['#1565c0', '#ff9933'], a: ['Little Master', 'Sachin'], en: 'calm', langs: ['hi', 'en'] }),
  p('babar-azam', 'Babar Azam', 'بابر أعظم', 'PK', 'm', 78, 'Cricket',
    "Pakistan's elegant star batter",
    'calm, classy, reserved',
    { l: 'short/beard', c: ['#01411c', '#ffffff'], a: ['Babar'], en: 'calm', langs: ['ur', 'en'] }),
  p('shohei-ohtani', 'Shohei Ohtani', 'شوهي أوتاني', 'JP', 'm', 86, 'Baseball',
    'Two-way Japanese superstar who pitches and hits at an MVP level',
    'polite, humble, unbelievably dedicated',
    { l: 'short/none/cap/jersey', c: ['#005a9c', '#ef3e42'], a: ['Shotime', 'Ohtani'], en: 'calm', langs: ['ja', 'en'] }),
  p('tom-brady', 'Tom Brady', 'توم برادي', 'US', 'm', 84, 'NFL quarterback',
    'Seven-time Super Bowl champion quarterback',
    'competitive, disciplined, wellness-obsessed',
    { l: 'short/stubble/none/suit', e: 'legend', c: ['#002244', '#c60c30'], a: ['TB12', 'Brady', 'The GOAT'] }),
  p('patrick-mahomes', 'Patrick Mahomes', 'باتريك ماهومز', 'US', 'm', 80, 'NFL quarterback',
    "Kansas City's magic-armed Super Bowl-winning quarterback",
    'playful, creative, confident',
    { l: 'curly', c: ['#e31837', '#ffb81c'], a: ['Mahomes', 'Showtime'] }),
  p('mo-farah', 'Mo Farah', 'مو فرح', 'GB', 'm', 74, 'Distance runner',
    'Four-time Olympic champion born in Somalia',
    'warm, resilient, family man',
    { l: 'bald/stubble', e: 'legend', c: ['#012169', '#c8102e'], a: ['Mo', 'Mobot'], en: 'warm' }),
  p('eliud-kipchoge', 'Eliud Kipchoge', 'إليود كيبتشوغي', 'KE', 'm', 76, 'Marathoner',
    'Kenyan marathon great who ran the first sub-two-hour marathon',
    'serene, philosophical, disciplined',
    { l: 'buzz', e: 'legend', c: ['#006600', '#bb0000'], a: ['Kipchoge'], s: ['No human is limited.'], en: 'calm' }),
  p('mutaz-barshim', 'Mutaz Essa Barshim', 'معتز عيسى برشم', 'QA', 'm', 74, 'High jumper',
    "Qatari Olympic high-jump champion who famously shared gold in Tokyo",
    'sporting, joyful, humble',
    { l: 'short/beard', c: ['#8a1538', '#ffffff'], a: ['Barshim', 'برشم', 'Mutaz'], langs: ['ar', 'en'], en: 'warm' }),
  p('nasser-al-attiyah', 'Nasser Al-Attiyah', 'ناصر العطية', 'QA', 'm', 74, 'Rally driver',
    'Multiple-time Dakar Rally winner and Olympic shooting medallist',
    'fearless, confident, desert-born racer',
    { l: 'short/beard/ghutra', c: ['#8a1538', '#ffffff'], a: ['Nasser', 'العطية'], env: 'track', langs: ['ar', 'en'] }),
  p('yazeed-al-rajhi', 'Yazeed Al-Rajhi', 'يزيد الراجحي', 'SA', 'm', 66, 'Rally driver',
    'Saudi rally driver and Dakar Rally champion',
    'calm under pressure, proud, determined',
    { l: 'short/beard/ghutra', c: ['#006c35', '#ffffff'], a: ['Yazeed', 'الراجحي'], langs: ['ar', 'en'], d: '2026-09-14' }),
  p('ahmed-hafnaoui', 'Ahmed Hafnaoui', 'أحمد الحفناوي', 'TN', 'm', 62, 'Swimmer',
    "Tunisian Olympic 400m freestyle champion",
    'shy, ambitious, hardworking',
    { l: 'short', e: 'rising', c: ['#e70013', '#00b0ff'], a: ['Hafnaoui', 'الحفناوي'], langs: ['ar', 'fr', 'en'] }),
]);
